Repository BinaryStudioAcademy/bsa-2021-perflow, pull requests merged in 2021-08, with the labels that each got.

#16 Bugfix/main menu
  frontend/angular.json
  frontend/src/app/app-routing.module.ts
  frontend/src/app/moduls/main/main-home/main-home.component.html
  frontend/src/app/moduls/main/main-menu/main-menu.component.html
  frontend/src/app/moduls/main/main-menu/main-menu.component.sass
  frontend/src/app/moduls/main/main-menu/main-menu.component.ts
  frontend/src/app/moduls/main/main-routing.module.ts
  frontend/src/app/services/auth.service.ts
Labels: bug

#19 Feature/user registration page
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.component.html
  frontend/src/app/app.module.ts
  frontend/src/app/models/auth/user-register.ts
  frontend/src/app/moduls/register/user-registration-form/user-registration-form/user-registration-form.component.html
  frontend/src/app/moduls/register/user-registration-form/user-registration-form/user-registration-form.component.sass
  frontend/src/app/moduls/register/user-registration-form/user-registration-form/user-registration-form.component.spec.ts
  frontend/src/app/moduls/register/user-registration-form/user-registration-form/user-registration-form.component.ts
  frontend/src/app/moduls/register/user-registration-page/user-registration-page.component.html
  frontend/src/app/moduls/register/user-registration-page/user-registration-page.component.sass
  frontend/src/app/moduls/register/user-registration-page/user-registration-page.component.spec.ts
  frontend/src/app/moduls/register/user-registration-page/user-registration-page.component.ts
  frontend/src/app/moduls/register/user-registration-routing.module.ts
  frontend/src/app/moduls/register/user-registration.module.ts
  frontend/src/app/services/http-internal.service.ts
  frontend/src/app/services/user.service.ts
  frontend/src/assets/LandingPageSideImage.jpg
  frontend/src/index.html
  frontend/src/styles.sass
Labels: enhancement

#22 Add song toolbar, provide ability to control listening and see music's info
  frontend/.eslintrc.json
  frontend/src/app/app.module.ts
  frontend/src/app/components/shared/song-toolbar/song-toolbar.component.html
  frontend/src/app/components/shared/song-toolbar/song-toolbar.component.sass
  frontend/src/app/components/shared/song-toolbar/song-toolbar.component.spec.ts
  frontend/src/app/components/shared/song-toolbar/song-toolbar.component.ts
  frontend/src/app/directives/shared/show/show-hide.directive.spec.ts
  frontend/src/app/directives/shared/show/show-hide.directive.ts
  frontend/src/app/helpers/TimeConverter.ts
  frontend/src/app/models/shared/SongInfo.ts
  frontend/src/styles.sass
Labels: enhancement

#20 Feature/create main component
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/moduls/main/cards/calm-rhythms-card/calm-rhythms-card.component.html
  frontend/src/app/moduls/main/cards/calm-rhythms-card/calm-rhythms-card.component.sass
  frontend/src/app/moduls/main/cards/calm-rhythms-card/calm-rhythms-card.component.spec.ts
  frontend/src/app/moduls/main/cards/calm-rhythms-card/calm-rhythms-card.component.ts
  frontend/src/app/moduls/main/cards/new-releases-card/new-releases-card.component.html
  frontend/src/app/moduls/main/cards/new-releases-card/new-releases-card.component.sass
  frontend/src/app/moduls/main/cards/new-releases-card/new-releases-card.component.spec.ts
  frontend/src/app/moduls/main/cards/new-releases-card/new-releases-card.component.ts
  frontend/src/app/moduls/main/cards/recently-played-card/recently-played-card.component.html
  frontend/src/app/moduls/main/cards/recently-played-card/recently-played-card.component.sass
  frontend/src/app/moduls/main/cards/recently-played-card/recently-played-card.component.spec.ts
  frontend/src/app/moduls/main/cards/recently-played-card/recently-played-card.component.ts
  frontend/src/app/moduls/main/cards/top-songs-card/top-songs-card.component.html
  frontend/src/app/moduls/main/cards/top-songs-card/top-songs-card.component.sass
  frontend/src/app/moduls/main/cards/top-songs-card/top-songs-card.component.spec.ts
  frontend/src/app/moduls/main/cards/top-songs-card/top-songs-card.component.ts
  frontend/src/app/moduls/main/cards/your-mix-card/your-mix-card.component.html
  frontend/src/app/moduls/main/cards/your-mix-card/your-mix-card.component.sass
  frontend/src/app/moduls/main/cards/your-mix-card/your-mix-card.component.spec.ts
  frontend/src/app/moduls/main/cards/your-mix-card/your-mix-card.component.ts
  frontend/src/app/moduls/main/main-home/main-home.component.html
  frontend/src/app/moduls/main/main-home/main-home.component.sass
  frontend/src/app/moduls/main/main-home/main-home.component.ts
  frontend/src/app/moduls/main/main-menu/main-menu.component.sass
  frontend/src/app/moduls/main/main.module.ts
  frontend/src/app/moduls/main/profile-menu/profile-menu.component.html
  frontend/src/app/moduls/main/profile-menu/profile-menu.component.sass
  frontend/src/app/moduls/main/profile-menu/profile-menu.component.spec.ts
  frontend/src/app/moduls/main/profile-menu/profile-menu.component.ts
  frontend/src/styles.sass
Labels: enhancement

#24 Implement ability to like a song
  backend/Perflow/Common/DTO/Enums/AuthorType.cs
  backend/Perflow/Common/DTO/Reactions/NewSongReactionDTO.cs
  backend/Perflow/Common/DTO/Song/SongDTO.cs
  backend/Perflow/Common/DTO/User/ArtistFollowerDTO.cs
  backend/Perflow/Common/MappingProfiles/SongProfile.cs
  backend/Perflow/Common/MappingProfiles/SongReactionProfile.cs
  backend/Perflow/Controllers/SongReactionController.cs
  backend/Perflow/DataAccess/Context/EntityTypeConfigurations/SongReactionConfiguration.cs
  backend/Perflow/Domain/User.cs
  backend/Perflow/Services/Extensions/ServiceExtensions.cs
  backend/Perflow/Services/SongReactionService.cs
  backend/Perflow/Startup.cs
  frontend/src/app/moduls/register/user-registration-form/user-registration-form/user-registration-form.component.ts
  frontend/src/app/moduls/register/user-registration-page/user-registration-page.component.ts
  frontend/src/app/services/reaction.service.ts
Labels: enhancement

#25 Feature/change-song-to-album-relationship
  backend/Perflow/DataAccess/Context/EntityTypeConfigurations/AlbumConfiguration.cs
  backend/Perflow/DataAccess/Context/EntityTypeConfigurations/SongConfiguration.cs
  backend/Perflow/DataAccess/Context/ModelBuilderExtensions.cs
  backend/Perflow/DataAccess/Context/PerflowContext.cs
  backend/Perflow/Domain/Song.cs
  backend/Perflow/Migrations/20210803111753_ChangeSongToAlbumRelationship.Designer.cs
  backend/Perflow/Migrations/20210803111753_ChangeSongToAlbumRelationship.cs
  backend/Perflow/Migrations/PerflowContextModelSnapshot.cs
  backend/Perflow/Startup.cs
  backend/Perflow/seed.sql
Labels: help wanted

#18 Create landing page
  frontend/package-lock.json
  frontend/src/app/app.module.ts
  frontend/src/app/components/landing-page/landing-page.component.html
  frontend/src/app/components/landing-page/landing-page.component.sass
  frontend/src/app/components/landing-page/landing-page.component.ts
  frontend/src/styles.sass
Labels: enhancement, help wanted

#21 Feature/add song row component
  frontend/angular.json
  frontend/package.json
  frontend/src/app/app.module.ts
  frontend/src/app/components/shared/song-row/song-row.component.html
  frontend/src/app/components/shared/song-row/song-row.component.sass
  frontend/src/app/components/shared/song-row/song-row.component.spec.ts
  frontend/src/app/components/shared/song-row/song-row.component.ts
  frontend/src/app/directives/shared/dropdown/semantic-dropdown.directive.spec.ts
  frontend/src/app/directives/shared/dropdown/semantic-dropdown.directive.ts
  frontend/src/app/models/shared/album.model.ts
  frontend/src/app/models/shared/artist.model.ts
  frontend/src/app/models/shared/song.model.ts
  frontend/src/assets/images/playlist.svg
  frontend/src/assets/images/streaming.svg
  frontend/tsconfig.app.json
  frontend/tsconfig.json
Labels: enhancement

#26 Add and configure husky
  .husky/pre-commit
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.component.ts
  frontend/src/app/app.module.ts
  frontend/src/app/components/shared/song-row/song-row.component.html
  frontend/src/app/components/shared/song-row/song-row.component.spec.ts
  frontend/src/app/components/shared/song-row/song-row.component.ts
  frontend/src/app/directives/shared/dropdown/semantic-dropdown.directive.ts
  frontend/src/app/interceptors/jwt/jwt.interceptor.spec.ts
  frontend/src/app/interceptors/jwt/jwt.interceptor.ts
  frontend/src/app/models/shared/album.model.ts
  frontend/src/app/models/shared/artist.model.ts
  frontend/src/app/models/shared/song.model.ts
  frontend/src/app/moduls/main/main.module.ts
  frontend/src/app/services/auth/auth.service.ts
  frontend/src/app/typings.d.ts
Labels: enhancement

#30 Feature/liked songs component
  backend/Perflow/Common/DTO/Albums/AlbumReadDTO.cs
  backend/Perflow/Common/DTO/Groups/GroupReadDTO.cs
  backend/Perflow/Common/DTO/Playlist/AccessTypeDTO.cs
  backend/Perflow/Common/DTO/Playlists/AccessTypeDTO.cs
  backend/Perflow/Common/DTO/Playlists/PlaylistDTO.cs
  backend/Perflow/Common/DTO/Song/SongDTO.cs
  backend/Perflow/Common/DTO/Songs/SongReadDTO.cs
  backend/Perflow/Common/DTO/Users/ArtistFollowerDTO.cs
  backend/Perflow/Common/DTO/Users/ArtistReadDTO.cs
  backend/Perflow/Common/DTO/Users/UserReadDTO.cs
  backend/Perflow/Common/MappingProfiles/AlbumProfile.cs
  backend/Perflow/Common/MappingProfiles/GroupProfile.cs
  backend/Perflow/Common/MappingProfiles/PlaylistProfile.cs
  backend/Perflow/Common/MappingProfiles/SongProfile.cs
  backend/Perflow/Common/MappingProfiles/UserProfile.cs
  backend/Perflow/Controllers/PlaylistsController.cs
  backend/Perflow/Controllers/SongsController.cs
  backend/Perflow/DataAccess/Context/ModelBuilderExtensions.cs
  backend/Perflow/Domain/Album.cs
  backend/Perflow/Services/Extensions/ServiceExtensions.cs
  backend/Perflow/Services/Implementations/PlaylistService.cs
  backend/Perflow/Services/Implementations/SongsService.cs
  backend/Perflow/Services/Interfaces/ISongsService.cs
  frontend/src/app/directives/shared/dropdown/semantic-dropdown.directive.spec.ts
  frontend/src/app/directives/shared/show/show-hide.directive.spec.ts
  frontend/src/app/models/shared/SongInfo.ts
  frontend/src/app/modules/main/main.module.ts
  frontend/src/app/modules/main/songs/songs.component.html
  frontend/src/app/modules/main/songs/songs.component.sass
  frontend/src/app/modules/main/songs/songs.component.ts
  frontend/src/app/services/songs/songs.service.ts
Labels: enhancement

#32 Feature/refactor perflow
  backend/Perflow/Authorization/AuthorizationService.cs
  backend/Perflow/Common/DTO/Enums/AuthorType.cs
  backend/Perflow/Common/DTO/Playlists/PlaylistDTO.cs
  backend/Perflow/Common/DTO/Reactions/NewSongReactionDTO.cs
  backend/Perflow/Common/DTO/Songs/SongReadDTO.cs
  backend/Perflow/Common/MappingProfiles/AlbumReactionProfile.cs
  backend/Perflow/Common/MappingProfiles/ArtistReactionProfile.cs
  backend/Perflow/Common/MappingProfiles/NotificationProfile.cs
  backend/Perflow/Common/MappingProfiles/PlaylistReactionProfile.cs
  backend/Perflow/Common/MappingProfiles/RoleProfile.cs
  backend/Perflow/Common/MappingProfiles/SongReactionProfile.cs
  backend/Perflow/Common/MappingProfiles/UserSettingsProfile.cs
  backend/Perflow/Controllers/PlaylistsController.cs
  backend/Perflow/DataAccess/Context/EntityTypeConfigurations/ArtistFollowerConfiguration.cs
  backend/Perflow/DataAccess/Context/EntityTypeConfigurations/NotificationConfiguration.cs
  backend/Perflow/Domain/Abstract/AuditEntity.cs
  backend/Perflow/Domain/Abstract/BaseEntity.cs
  backend/Perflow/Domain/Album.cs
  backend/Perflow/Domain/ArtistFollower.cs
  backend/Perflow/Domain/Enums/AlbumRegion.cs
  backend/Perflow/Domain/Enums/AudioQuality.cs
  backend/Perflow/Domain/Enums/AuthorType.cs
  backend/Perflow/Domain/Group.cs
  backend/Perflow/Domain/Notification.cs
  backend/Perflow/Domain/Playlist.cs
  backend/Perflow/Domain/PlaylistSong.cs
  backend/Perflow/Program.cs
  backend/Perflow/Services/Abstract/BaseService.cs
  backend/Perflow/Services/Extensions/ServiceExtensions.cs
  backend/Perflow/Services/Implementations/PlaylistService.cs
  backend/Perflow/Services/Implementations/SongsService.cs
  backend/Perflow/Services/SongReactionService.cs
Labels: Refactoring

#33 Fix frontend import errors
  frontend/src/app/helpers/sort-compare-functions.ts
  frontend/src/app/models/album/album.ts
  frontend/src/app/models/enums/author-type.enum.ts
  frontend/src/app/models/song/song-sort-type.ts
  frontend/src/app/models/song/song.ts
  frontend/src/app/models/user/user.ts
  frontend/src/app/modules/auth/auth.module.ts
  frontend/src/app/modules/main/songs/songs.component.ts
  frontend/src/app/modules/shared/pipes/sort-songs.pipe.ts
  frontend/src/app/modules/shared/songs-list-header/songs-list-header.component.ts
  frontend/src/app/modules/shared/songs-list-header/sort-order-icon/sort-order-icon.component.ts
  frontend/src/app/modules/shared/songs-list/songs-list.component.ts
  frontend/src/app/services/songs/songs.service.ts
Labels: bug, important

#28 Feature/load albums from backend, edit ocelot api ports and routes
  backend/ApiGateway/ApiGateway/Properties/launchSettings.json
  backend/ApiGateway/ApiGateway/configuration.json
  backend/Perflow/Common/DTO/Albums/AlbumViewDTO.cs
  backend/Perflow/Common/DTO/Songs/SongViewDTO.cs
  backend/Perflow/Common/DTO/Users/UserReadDTO.cs
  backend/Perflow/Common/MappingProfiles/AlbumProfile.cs
  backend/Perflow/Common/MappingProfiles/SongProfile.cs
  backend/Perflow/Controllers/AlbumsController.cs
  backend/Perflow/DataAccess/Context/ModelBuilderExtensions.cs
  backend/Perflow/Migrations/PerflowContextModelSnapshot.cs
  backend/Perflow/Perflow.csproj
  backend/Perflow/Services/Extensions/ServiceExtensions.cs
  backend/Perflow/Services/Implementations/AlbumsService.cs
  backend/Perflow/Startup.cs
  backend/Perflow/appsettings.json
  backend/Perflow/seed.sql
  frontend/src/app/models/album/album-view.ts
  frontend/src/app/models/song/song-view.ts
  frontend/src/app/modules/main/cards/new-releases-card/new-releases-card.component.html
  frontend/src/app/modules/main/cards/new-releases-card/new-releases-card.component.sass
  frontend/src/app/modules/main/cards/new-releases-card/new-releases-card.component.ts
  frontend/src/app/modules/main/main-home/main-home.component.html
  frontend/src/app/modules/main/main-home/main-home.component.ts
  frontend/src/app/services/album.service.ts
Labels: enhancement

#37 Remove seeding from ContextModelSnapshot
  backend/Perflow/Migrations/PerflowContextModelSnapshot.cs
Labels: bug

#35 Add playlists/albums page, add common styles for playlist card
  backend/Perflow/Common/DTO/Albums/AlbumForListDTO.cs
  backend/Perflow/Common/DTO/Reactions/NewAlbumReactionDTO.cs
  backend/Perflow/Common/DTO/Reactions/NewArtistReactionDTO.cs
  backend/Perflow/Common/DTO/Users/ArtistReadDTO.cs
  backend/Perflow/Common/MappingProfiles/AlbumProfile.cs
  backend/Perflow/Common/MappingProfiles/ArtistProfile.cs
  backend/Perflow/Controllers/AlbumReactionController.cs
  backend/Perflow/Controllers/ArtistReactionController.cs
  backend/Perflow/Controllers/SongReactionController.cs
  backend/Perflow/DataAccess/Context/EntityTypeConfigurations/AlbumConfiguration.cs
  backend/Perflow/DataAccess/Context/EntityTypeConfigurations/UserConfiguration.cs
  backend/Perflow/DataAccess/Context/ModelBuilderExtensions.cs
  backend/Perflow/Domain/User.cs
  backend/Perflow/Services/Extensions/ServiceExtensions.cs
  backend/Perflow/Services/Implementations/AlbumReactionService.cs
  backend/Perflow/Services/Implementations/ArtistReactionService.cs
  backend/Perflow/Services/Implementations/SongReactionService.cs
  frontend/package.json
  frontend/src/app/directives/shared/dropdown/semantic-dropdown.directive.ts
  frontend/src/app/models/album/albumForReadDTO.ts
  frontend/src/app/models/user/ArtistReadDTO.ts
  frontend/src/app/modules/main/cards/album-card/album-card.component.html
  frontend/src/app/modules/main/cards/album-card/album-card.component.sass
  frontend/src/app/modules/main/cards/album-card/album-card.component.spec.ts
  frontend/src/app/modules/main/cards/album-card/album-card.component.ts
  frontend/src/app/modules/main/cards/artist-card/artist-card.component.html
  frontend/src/app/modules/main/cards/artist-card/artist-card.component.sass
  frontend/src/app/modules/main/cards/artist-card/artist-card.component.spec.ts
  frontend/src/app/modules/main/cards/artist-card/artist-card.component.ts
  frontend/src/app/modules/main/cards/playlist-card-styles.sass
  frontend/src/app/modules/main/main-home/main-home.component.html
  frontend/src/app/modules/main/main-menu-profile/main-menu-profile.component.html
  frontend/src/app/modules/main/main-menu-profile/main-menu-profile.component.sass
  frontend/src/app/modules/main/main-menu-profile/main-menu-profile.component.spec.ts
  frontend/src/app/modules/main/main-menu-profile/main-menu-profile.component.ts
  frontend/src/app/modules/main/main-routing.module.ts
  frontend/src/app/modules/main/main.module.ts
  frontend/src/app/modules/main/playlist/album-list/album-list.component.html
  frontend/src/app/modules/main/playlist/album-list/album-list.component.sass
  frontend/src/app/modules/main/playlist/album-list/album-list.component.spec.ts
  frontend/src/app/modules/main/playlist/album-list/album-list.component.ts
  frontend/src/app/modules/main/playlist/artist-list/artist-list.component.html
  frontend/src/app/modules/main/playlist/artist-list/artist-list.component.sass
  frontend/src/app/modules/main/playlist/artist-list/artist-list.component.spec.ts
  frontend/src/app/modules/main/playlist/artist-list/artist-list.component.ts
  frontend/src/app/modules/main/playlist/playlist.component.html
  frontend/src/app/modules/main/profile-menu/profile-menu.component.html
  frontend/src/app/modules/main/profile-menu/profile-menu.component.sass
  frontend/src/app/services/reaction.service.ts
  frontend/src/app/typings.d.ts
  frontend/src/styles.sass
  frontend/tsconfig.json
Labels: enhancement

#39 Feature/update scroll
  backend/Perflow/Common/Security/SecurityHelper.cs
  frontend/src/app/modules/main/main-home/main-home.component.sass
  frontend/src/app/modules/user/user-profile-edit/user-profile-edit.component.sass
  frontend/src/assets/images/standartIcon.png
  frontend/src/styles.sass
Labels: enhancement

#40 Feature/create page for creating editing playlist
  backend/Perflow/Common/DTO/Playlists/PlaylistSongDTO.cs
  backend/Perflow/Controllers/PlaylistsController.cs
  backend/Perflow/Controllers/SongsController.cs
  backend/Perflow/DataAccess/Context/PerflowContext.cs
  backend/Perflow/Services/Extensions/ServiceExtensions.cs
  backend/Perflow/Services/Implementations/PlaylistService.cs
  backend/Perflow/Services/Implementations/SongsService.cs
  backend/Perflow/Services/Interfaces/ISongsService.cs
  backend/Perflow/appsettings.json
  frontend/src/app/models/playlist/accessType.ts
  frontend/src/app/models/playlist/editedPlaylist.ts
  frontend/src/app/models/playlist/playlist.ts
  frontend/src/app/models/playlist/playlistSongDTO.ts
  frontend/src/app/modules/main/create-edit-playlist/create-edit-playlist/create-edit-playlist.component.html
  frontend/src/app/modules/main/create-edit-playlist/create-edit-playlist/create-edit-playlist.component.sass
  frontend/src/app/modules/main/create-edit-playlist/create-edit-playlist/create-edit-playlist.component.spec.ts
  frontend/src/app/modules/main/create-edit-playlist/create-edit-playlist/create-edit-playlist.component.ts
  frontend/src/app/modules/main/create-edit-playlist/edit-playlist-modal/edit-playlist-modal.component.html
  frontend/src/app/modules/main/create-edit-playlist/edit-playlist-modal/edit-playlist-modal.component.sass
  frontend/src/app/modules/main/create-edit-playlist/edit-playlist-modal/edit-playlist-modal.component.spec.ts
  frontend/src/app/modules/main/create-edit-playlist/edit-playlist-modal/edit-playlist-modal.component.ts
  frontend/src/app/modules/main/main-menu/main-menu.component.html
  frontend/src/app/modules/main/main-routing.module.ts
  frontend/src/app/modules/main/main.module.ts
  frontend/src/app/modules/shared/pipes/access-type.pipe.ts
  frontend/src/app/modules/shared/pipes/song-duration.pipe.ts
  frontend/src/app/modules/shared/shared.module.ts
  frontend/src/app/modules/shared/song-row/song-row.component.html
  frontend/src/app/modules/shared/song-row/song-row.component.ts
  frontend/src/app/modules/shared/songs-list/songs-list.component.html
  frontend/src/app/modules/shared/songs-list/songs-list.component.ts
  frontend/src/app/services/playlists/playlist.service.ts
  frontend/src/app/services/songs/songs.service.ts
Labels: enhancement

#45 Create/edit playlist page. Add add/remove buttons for song
  backend/ApiGateway/ApiGateway/configuration.Development.json
  backend/ApiGateway/ApiGateway/configuration.Production.json
  frontend/src/app/modules/main/create-edit-playlist/create-edit-playlist/create-edit-playlist.component.html
  frontend/src/app/modules/main/create-edit-playlist/create-edit-playlist/create-edit-playlist.component.sass
  frontend/src/app/modules/main/create-edit-playlist/create-edit-playlist/create-edit-playlist.component.ts
  frontend/src/app/modules/shared/playlist/search-song-row/search-song-row.component.html
  frontend/src/app/modules/shared/playlist/search-song-row/search-song-row.component.sass
  frontend/src/app/modules/shared/playlist/search-song-row/search-song-row.component.spec.ts
  frontend/src/app/modules/shared/playlist/search-song-row/search-song-row.component.ts
  frontend/src/app/modules/shared/shared.module.ts
Labels: enhancement

#49 Fix "My playlist" playlist/album loading
  backend/ApiGateway/ApiGateway/configuration.Development.json
  backend/ApiGateway/ApiGateway/configuration.Production.json
  frontend/src/app/modules/auth/landing-page/landing-page.component.sass
  frontend/src/app/modules/main/playlist/all/all.component.html
  frontend/src/app/modules/main/playlist/all/all.component.sass
  frontend/src/app/modules/main/playlist/all/all.component.ts
  frontend/src/app/services/reaction.service.ts
Labels: bug

#46 add albums cards to album page
  frontend/package.json
  frontend/src/app/models/album/album.ts
  frontend/src/app/modules/album/album.module.ts
  frontend/src/app/modules/album/components/album-card/album-card.component.html
  frontend/src/app/modules/album/components/album-card/album-card.component.sass
  frontend/src/app/modules/album/components/album-card/album-card.component.spec.ts
  frontend/src/app/modules/album/components/album-card/album-card.component.ts
  frontend/src/app/modules/album/components/album-details/album-details.component.html
  frontend/src/app/modules/album/components/album-details/album-details.component.sass
  frontend/src/app/modules/album/components/album-details/album-details.component.ts
  frontend/src/app/modules/main/main.module.ts
  frontend/src/app/modules/shared/song-row/song-row.component.html
  frontend/src/app/modules/user/profile-edit-form/profile-edit-form.component.ts
  frontend/src/app/modules/user/update-password-form/update-password-form.component.ts
Labels: enhancement

#54 Added ability to dislike liked songs on page 'Liked songs'
  backend/ApiGateway/ApiGateway/configuration.Development.json
  backend/ApiGateway/ApiGateway/configuration.Production.json
  frontend/src/app/modules/main/songs/songs.component.html
  frontend/src/app/modules/main/songs/songs.component.ts
  frontend/src/app/modules/shared/song-row/song-row.component.html
  frontend/src/app/modules/shared/song-row/song-row.component.ts
  frontend/src/app/modules/shared/songs-list/songs-list.component.html
  frontend/src/app/modules/shared/songs-list/songs-list.component.ts
Labels: enhancement

#55 Feature/add artist page
  backend/ApiGateway/ApiGateway/configuration.Development.json
  backend/ApiGateway/ApiGateway/configuration.Production.json
  backend/Perflow/Common/DTO/Albums/AlbumForArtistDTO.cs
  backend/Perflow/Common/DTO/Playlists/PlaylistViewDTO.cs
  backend/Perflow/Common/DTO/Users/ArtistDTO.cs
  backend/Perflow/Common/MappingProfiles/AlbumProfile.cs
  backend/Perflow/Common/MappingProfiles/PlaylistProfile.cs
  backend/Perflow/Common/MappingProfiles/UserProfile.cs
  backend/Perflow/Controllers/ArtistsController.cs
  backend/Perflow/Controllers/PlaylistsController.cs
  backend/Perflow/Controllers/SongsController.cs
  backend/Perflow/Services/Extensions/ServiceExtensions.cs
  backend/Perflow/Services/Implementations/AlbumsService.cs
  backend/Perflow/Services/Implementations/ArtistService.cs
  backend/Perflow/Services/Implementations/PlaylistService.cs
  backend/Perflow/Services/Implementations/SongsService.cs
  backend/Perflow/Services/Interfaces/IArtistService.cs
  backend/Perflow/Services/Interfaces/ISongsService.cs
  frontend/src/app/directives/shared/dropdown/semantic-dropdown.directive.ts
  frontend/src/app/models/playlist/playlist-view.ts
  frontend/src/app/models/user/artist.ts
  frontend/src/app/modules/artist/artist-routing.module.ts
  frontend/src/app/modules/artist/artist.module.ts
  frontend/src/app/modules/artist/components/artist-details/artist-details.component.html
  frontend/src/app/modules/artist/components/artist-details/artist-details.component.sass
  frontend/src/app/modules/artist/components/artist-details/artist-details.component.spec.ts
  frontend/src/app/modules/artist/components/artist-details/artist-details.component.ts
  frontend/src/app/modules/artist/components/playlist-card/playlist-card.component.html
  frontend/src/app/modules/artist/components/playlist-card/playlist-card.component.sass
  frontend/src/app/modules/artist/components/playlist-card/playlist-card.component.spec.ts
  frontend/src/app/modules/artist/components/playlist-card/playlist-card.component.ts
  frontend/src/app/modules/main/main-routing.module.ts
  frontend/src/app/modules/shared/song-row/song-row.component.html
  frontend/src/app/services/artist.service.ts
  frontend/src/app/services/playlists/playlist.service.ts
  frontend/src/app/services/songs/songs.service.ts
Labels: enhancement

#56 Feature/load created playlists
  backend/Perflow/Controllers/PlaylistsController.cs
  backend/Perflow/Services/Implementations/PlaylistService.cs
  backend/Perflow/seed.sql
  frontend/src/app/modules/main/main-menu/main-menu.component.ts
  frontend/src/app/services/playlists/playlist.service.ts
Labels: enhancement

#51 Set up blob storage emulator locally
  backend/Perflow/Common/DTO/Songs/SongWriteDTO.cs
  backend/Perflow/Common/MappingProfiles/SongProfile.cs
  backend/Perflow/Controllers/SongsController.cs
  backend/Perflow/Services/Extensions/ServiceExtensions.cs
  backend/Perflow/Services/Implementations/SongsService.cs
  backend/Perflow/Services/Interfaces/ISongsService.cs
  backend/Shared/Shared/AzureBlobStorage/Helpers/FileTransformer.cs
  backend/Shared/Shared/AzureBlobStorage/Interfaces/IBlobService.cs
  backend/Shared/Shared/AzureBlobStorage/Models/BlobDto.cs
  backend/Shared/Shared/AzureBlobStorage/Services/BlobService.cs
  frontend/src/app/models/song/song-write.ts
  frontend/src/app/modules/main/main-menu-profile/main-menu-profile.component.html
  frontend/src/app/modules/main/main-menu-profile/main-menu-profile.component.ts
  frontend/src/app/modules/main/main-routing.module.ts
  frontend/src/app/modules/main/main.module.ts
  frontend/src/app/modules/main/songs/songs.component.ts
  frontend/src/app/modules/shared/song-toolbar/song-toolbar.component.sass
  frontend/src/app/modules/shared/song-toolbar/song-toolbar.component.ts
  frontend/src/app/services/song-toolbar.service.ts
  frontend/src/app/services/songs/songs.service.ts
  frontend/src/styles.sass
Labels: enhancement

#52 Add missing endpoints
  backend/ApiGateway/ApiGateway/configuration.Development.json
  backend/ApiGateway/ApiGateway/configuration.Production.json
Labels: enhancement

#58 Add settings page
  frontend/src/app/modules/main/main-routing.module.ts
  frontend/src/app/modules/main/main.module.ts
  frontend/src/app/modules/main/profile-menu/profile-menu.component.html
  frontend/src/app/modules/main/settings/settings.component.html
  frontend/src/app/modules/main/settings/settings.component.sass
  frontend/src/app/modules/main/settings/settings.component.spec.ts
  frontend/src/app/modules/main/settings/settings.component.ts
  frontend/src/styles.sass
Labels: enhancement

#59 add links; fix profile image; update changePassword method
  backend/Perflow/Controllers/UsersController.cs
  backend/Perflow/Services/Implementations/AuthService.cs
  backend/Perflow/Services/Interfaces/IAuthService.cs
  backend/Shared/Shared/Auth/Extensions/ClaimsExtensions.cs
  backend/Shared/Shared/Auth/Extensions/FirebaseExtensions.cs
  frontend/src/app/modules/main/cards/circle-info-card/circle-info-card.component.html
  frontend/src/app/modules/main/cards/circle-info-card/circle-info-card.component.ts
  frontend/src/app/modules/main/main-home/main-home.component.html
  frontend/src/app/modules/main/main-routing.module.ts
  frontend/src/app/modules/main/user-profile/user-profile.component.html
  frontend/src/app/modules/main/user-profile/user-profile.component.sass
  frontend/src/app/modules/main/user-profile/user-profile.component.ts
  frontend/src/app/modules/shared/playlist/search-song-row/search-song-row.component.html
  frontend/src/app/modules/shared/playlist/search-song-row/search-song-row.component.sass
  frontend/src/app/modules/shared/song-row/song-row.component.html
  frontend/src/app/modules/shared/song-row/song-row.component.sass
  frontend/src/app/modules/user/profile-edit-form/profile-edit-form.component.html
  frontend/src/app/modules/user/profile-edit-form/profile-edit-form.component.sass
  frontend/src/app/modules/user/update-password-form/update-password-form.component.ts
  frontend/src/app/modules/user/user-profile-edit/user-profile-edit.component.html
  frontend/src/app/modules/user/user-profile-edit/user-profile-edit.component.ts
  frontend/src/app/services/user.service.ts
Labels: bug

#62 Bugfix/when you click on create a playlist nothing happens
  frontend/src/app/modules/main/main-routing.module.ts
Labels: bug

#61 Play liked songs in toolbar
  backend/Perflow/Common/DTO/Songs/SongReadDTO.cs
  backend/Perflow/Common/DTO/Songs/SongWriteDTO.cs
  backend/Perflow/Controllers/SongsController.cs
  backend/Perflow/Domain/Song.cs
  backend/Perflow/Migrations/20210811110238_AddBlobId.Designer.cs
  backend/Perflow/Migrations/20210811110238_AddBlobId.cs
  backend/Perflow/Migrations/PerflowContextModelSnapshot.cs
  backend/Perflow/Services/Implementations/SongsService.cs
  backend/Perflow/Services/Interfaces/ISongsService.cs
  backend/Shared/Shared/AzureBlobStorage/Interfaces/IBlobService.cs
  backend/Shared/Shared/AzureBlobStorage/Models/BlobDto.cs
  backend/Shared/Shared/AzureBlobStorage/Services/BlobService.cs
  frontend/src/app/models/song/song-write.ts
  frontend/src/app/models/song/song.ts
  frontend/src/app/modules/main/playlist/playlist.component.ts
  frontend/src/app/modules/shared/mock-audio/links.ts
  frontend/src/app/modules/shared/song-row/song-row.component.html
  frontend/src/app/modules/shared/song-row/song-row.component.ts
  frontend/src/app/services/songs/songs.service.ts
Labels: enhancement

#60 Add basic structure of Perflow Studio page
  frontend/src/app/app-routing.module.ts
  frontend/src/app/guards/auth.guard.ts
  frontend/src/app/guards/perflow-studio.guard.ts
  frontend/src/app/modules/main/profile-menu/profile-menu.component.html
  frontend/src/app/modules/perflow-studio/albums-page/albums-page.component.html
  frontend/src/app/modules/perflow-studio/albums-page/albums-page.component.sass
  frontend/src/app/modules/perflow-studio/albums-page/albums-page.component.spec.ts
  frontend/src/app/modules/perflow-studio/albums-page/albums-page.component.ts
  frontend/src/app/modules/perflow-studio/left-side-menu/left-side-menu.component.html
  frontend/src/app/modules/perflow-studio/left-side-menu/left-side-menu.component.sass
  frontend/src/app/modules/perflow-studio/left-side-menu/left-side-menu.component.spec.ts
  frontend/src/app/modules/perflow-studio/left-side-menu/left-side-menu.component.ts
  frontend/src/app/modules/perflow-studio/main-page/main-page.component.html
  frontend/src/app/modules/perflow-studio/main-page/main-page.component.sass
  frontend/src/app/modules/perflow-studio/main-page/main-page.component.spec.ts
  frontend/src/app/modules/perflow-studio/main-page/main-page.component.ts
  frontend/src/app/modules/perflow-studio/perflow-studio-routing.module.ts
  frontend/src/app/modules/perflow-studio/perflow-studio.module.ts
  frontend/src/app/modules/perflow-studio/playlists-page/playlists-page.component.html
  frontend/src/app/modules/perflow-studio/playlists-page/playlists-page.component.sass
  frontend/src/app/modules/perflow-studio/playlists-page/playlists-page.component.spec.ts
  frontend/src/app/modules/perflow-studio/playlists-page/playlists-page.component.ts
Labels: enhancement

#65 Add firebase api key to env
  frontend/angular.json
  frontend/custom-webpack.config.js
  frontend/src/app/typings.d.ts
  frontend/src/environments/environment.prod.ts
  frontend/src/environments/environment.ts
Labels: enhancement, important

#63 Feature/flutter
  mobile/.gitignore
  mobile/.metadata
  mobile/README.md
  mobile/analysis_options.yaml
  mobile/android/.gitignore
  mobile/android/app/build.gradle
  mobile/android/app/src/main/AndroidManifest.xml
  mobile/android/app/src/main/kotlin/com/example/mobile/MainActivity.kt
  mobile/android/app/src/main/res/drawable-v21/launch_background.xml
  mobile/android/app/src/main/res/drawable/launch_background.xml
  mobile/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  mobile/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  mobile/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  mobile/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  mobile/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  mobile/android/app/src/main/res/values-night/styles.xml
  mobile/android/app/src/main/res/values/styles.xml
  mobile/android/app/src/profile/AndroidManifest.xml
  mobile/android/build.gradle
  mobile/android/gradle.properties
  mobile/android/gradle/wrapper/gradle-wrapper.properties
  mobile/android/settings.gradle
  mobile/google_fonts/Rubik-Black.ttf
  mobile/google_fonts/Rubik-BlackItalic.ttf
  mobile/google_fonts/Rubik-Bold.ttf
  mobile/google_fonts/Rubik-BoldItalic.ttf
  mobile/google_fonts/Rubik-ExtraBold.ttf
  mobile/google_fonts/Rubik-ExtraBoldItalic.ttf
  mobile/google_fonts/Rubik-Italic.ttf
  mobile/google_fonts/Rubik-Light.ttf
  mobile/google_fonts/Rubik-LightItalic.ttf
  mobile/google_fonts/Rubik-Medium.ttf
  mobile/google_fonts/Rubik-MediumItalic.ttf
  mobile/google_fonts/Rubik-Regular.ttf
  mobile/google_fonts/Rubik-SemiBold.ttf
  mobile/google_fonts/Rubik-SemiBoldItalic.ttf
  mobile/lib/configure_services.config.dart
  mobile/lib/configure_services.dart
  mobile/lib/cubits/main_navigation/main_navigation_cubit.dart
  mobile/lib/cubits/main_navigation/main_navigation_cubit.freezed.dart
  mobile/lib/cubits/main_navigation/main_navigation_state.dart
  mobile/lib/helpers/get_service.dart
  mobile/lib/main.dart
  mobile/lib/models/delete_when_needed
  mobile/lib/perflow_app.dart
  mobile/lib/routes.dart
  mobile/lib/routes/auth_routes.dart
  mobile/lib/routes/guards/delete_when_needed
  mobile/lib/routes/main_routes.dart
  mobile/lib/screens/home/home_screen.dart
  mobile/lib/screens/main/main_screen.dart
  mobile/lib/screens/playlists/playlists_screen.dart
  mobile/lib/screens/search/search_screen.dart
  mobile/lib/services/playback_service.dart
  mobile/lib/theme.dart
  mobile/lib/widgets/delete_when_needed
  mobile/pubspec.lock
  mobile/pubspec.yaml
  mobile/test/widget_test.dart
Labels: enhancement

#68 Create playlist by user id
  frontend/src/app/modules/main/create-edit-playlist/create-edit-playlist/create-edit-playlist.component.ts
Labels: Refactoring

#70 Fix main menu highlight bug
  frontend/src/app/modules/main/main-menu/main-menu.component.html
  frontend/src/app/modules/main/main-routing.module.ts
Labels: bug

#69 Perflow Studio: load albums by artist
  frontend/src/app/guards/perflow-studio.guard.ts
  frontend/src/app/modules/main/main.module.ts
  frontend/src/app/modules/perflow-studio/albums-page/albums-page.component.html
  frontend/src/app/modules/perflow-studio/albums-page/albums-page.component.sass
  frontend/src/app/modules/perflow-studio/albums-page/albums-page.component.ts
  frontend/src/app/modules/perflow-studio/left-side-menu/left-side-menu.component.html
  frontend/src/app/modules/perflow-studio/left-side-menu/left-side-menu.component.sass
  frontend/src/app/modules/perflow-studio/main-page/main-page.component.html
  frontend/src/app/modules/perflow-studio/main-page/main-page.component.sass
Labels: enhancement

#75 fix album links
  frontend/src/app/modules/main/cards/album-card/album-card.component.html
  frontend/src/app/modules/main/playlist/all/all.component.html
  frontend/src/app/modules/shared/directives/stopPropagation/click-stop-propagation.directive.ts
  frontend/src/app/modules/shared/shared.module.ts
Labels: bug

#74 Added a real user name on Liked Songs
  frontend/src/app/modules/main/songs/songs.component.html
  frontend/src/app/modules/main/songs/songs.component.ts
Labels: enhancement

#73 Fix project id configuration
  backend/Perflow.Studio/Startup.cs
  backend/Perflow.Studio/appsettings.json
  backend/Perflow/Startup.cs
  backend/Shared/Shared/Auth/Extensions/AddAuthExtension.cs
Labels: bug

#71 Feature/create page for creating editing albums
  backend/ApiGateway/ApiGateway/configuration.Development.json
  backend/ApiGateway/ApiGateway/configuration.Production.json
  backend/Perflow/Common/DTO/Albums/AlbumEditDTO.cs
  backend/Perflow/Common/DTO/Albums/AlbumFullDTO.cs
  backend/Perflow/Common/MappingProfiles/AlbumProfile.cs
  backend/Perflow/Common/MappingProfiles/ArtistProfile.cs
  backend/Perflow/Controllers/AlbumsController.cs
  backend/Perflow/Controllers/GroupsController.cs
  backend/Perflow/Services/Extensions/ServiceExtensions.cs
  backend/Perflow/Services/Implementations/AlbumsService.cs
  backend/Perflow/Services/Implementations/ArtistService.cs
  backend/Perflow/Services/Implementations/GroupService.cs
  backend/Perflow/Services/Interfaces/IArtistService.cs
  frontend/src/app/models/album/album-edit.ts
  frontend/src/app/models/album/album-full.ts
  frontend/src/app/models/album/album-region.ts
  frontend/src/app/modules/album/album-routing.module.ts
  frontend/src/app/modules/album/album.module.ts
  frontend/src/app/modules/album/components/create-edit-album/create-edit-album/create-edit-album.component.html
  frontend/src/app/modules/album/components/create-edit-album/create-edit-album/create-edit-album.component.sass
  frontend/src/app/modules/album/components/create-edit-album/create-edit-album/create-edit-album.component.spec.ts
  frontend/src/app/modules/album/components/create-edit-album/create-edit-album/create-edit-album.component.ts
  frontend/src/app/modules/album/components/create-edit-album/edit-album-modal/edit-album-modal.component.html
  frontend/src/app/modules/album/components/create-edit-album/edit-album-modal/edit-album-modal.component.sass
  frontend/src/app/modules/album/components/create-edit-album/edit-album-modal/edit-album-modal.component.spec.ts
  frontend/src/app/modules/album/components/create-edit-album/edit-album-modal/edit-album-modal.component.ts
  frontend/src/app/modules/main/create-edit-playlist/edit-playlist-modal/edit-playlist-modal.component.sass
  frontend/src/app/modules/perflow-studio/albums-page/albums-page.component.ts
  frontend/src/app/modules/shared/directives/stopPropagation/click-stop-propagation.directive.ts
  frontend/src/app/modules/shared/pipes/album-author-type.pipe.ts
  frontend/src/app/modules/shared/pipes/album-region-type.pipe.ts
  frontend/src/app/modules/shared/shared.module.ts
  frontend/src/app/services/album.service.ts
  frontend/src/app/services/group.service.ts
  frontend/src/index.html
Labels: enhancement

#72 Feature/artist redirect on new releases
  backend/Perflow/Common/DTO/Albums/AlbumViewAuthorsDTO.cs
  backend/Perflow/Common/DTO/Albums/AlbumViewDTO.cs
  backend/Perflow/Controllers/AlbumsController.cs
  backend/Perflow/Services/Implementations/AlbumsService.cs
  backend/Perflow/seed.sql
  frontend/src/app/models/album/album-view.ts
  frontend/src/app/models/user/album-author.ts
  frontend/src/app/modules/main/cards/new-release-card/new-release-card/new-release-card.component.html
  frontend/src/app/modules/main/cards/new-release-card/new-release-card/new-release-card.component.sass
  frontend/src/app/modules/main/cards/new-release-card/new-release-card/new-release-card.component.spec.ts
  frontend/src/app/modules/main/cards/new-release-card/new-release-card/new-release-card.component.ts
  frontend/src/app/modules/main/main-home/main-home.component.html
  frontend/src/app/modules/main/main.module.ts
Labels: enhancement

#77 add ablility to like an album/song
  backend/Perflow/Common/DTO/Albums/AlbumFullDTO.cs
  backend/Perflow/Common/DTO/Songs/SongReadDTO.cs
  backend/Perflow/Common/Helpers/LikedSong.cs
  backend/Perflow/Common/MappingProfiles/SongProfile.cs
  backend/Perflow/Controllers/AlbumReactionController.cs
  backend/Perflow/Controllers/AlbumsController.cs
  backend/Perflow/Controllers/SongsController.cs
  backend/Perflow/Services/Implementations/AlbumReactionService.cs
  backend/Perflow/Services/Implementations/AlbumsService.cs
  backend/Perflow/Services/Implementations/SongsService.cs
  backend/Perflow/Services/Interfaces/ISongsService.cs
  frontend/src/app/models/album/album-full.ts
  frontend/src/app/models/song/song.ts
  frontend/src/app/modules/album/components/album-details/album-details.component.html
  frontend/src/app/modules/album/components/album-details/album-details.component.ts
  frontend/src/app/modules/album/components/create-edit-album/create-edit-album/create-edit-album.component.ts
  frontend/src/app/modules/artist/components/artist-details/artist-details.component.ts
  frontend/src/app/modules/main/songs/songs.component.html
  frontend/src/app/modules/main/songs/songs.component.ts
  frontend/src/app/modules/main/user-profile/user-profile.component.ts
  frontend/src/app/modules/shared/song-row/song-row.component.html
  frontend/src/app/modules/shared/song-row/song-row.component.sass
  frontend/src/app/modules/shared/song-row/song-row.component.ts
  frontend/src/app/modules/shared/songs-list/songs-list.component.html
  frontend/src/app/modules/shared/songs-list/songs-list.component.ts
  frontend/src/app/modules/user/user-profile-edit/user-profile-edit.component.ts
Labels: enhancement

#80 Feature/login spinner
  frontend/src/app/modules/auth/landing-page/landing-page.component.html
  frontend/src/app/modules/auth/landing-page/landing-page.component.sass
  frontend/src/app/modules/auth/landing-page/landing-page.component.ts
  frontend/src/app/modules/register/user-registration-form/user-registration-form/user-registration-form.component.html
  frontend/src/app/modules/register/user-registration-form/user-registration-form/user-registration-form.component.ts
Labels: enhancement

#82 Bugfix/edit new release authors routes
  frontend/src/app/modules/main/cards/new-release-card/new-release-card/new-release-card.component.html
Labels: bug

#83 Feature/liked songs real amount
  frontend/src/app/modules/artist/components/artist-details/artist-details.component.ts
  frontend/src/app/modules/main/playlist/all/all.component.html
  frontend/src/app/modules/main/playlist/all/all.component.ts
Labels: enhancement

#78 Profile menu icon changes, updates and corresponds to real user
  backend/ApiGateway/ApiGateway/configuration.Development.json
  backend/ApiGateway/ApiGateway/configuration.Production.json
  backend/Perflow/Common/DTO/Users/UserChangeIconDTO.cs
  backend/Perflow/Controllers/UsersController.cs
  backend/Perflow/Services/Implementations/UsersService.cs
  backend/Perflow/Services/Interfaces/IUsersService.cs
  frontend/src/app/models/user/user-change-icon.ts
  frontend/src/app/modules/main/profile-menu/profile-menu.component.html
  frontend/src/app/modules/main/profile-menu/profile-menu.component.ts
  frontend/src/app/modules/user/profile-edit-form/profile-edit-form.component.ts
  frontend/src/app/services/profile.service.ts
  frontend/src/app/services/user.service.ts
Labels: enhancement

#81 Feature/add logo
  frontend/src/app/modules/auth/landing-page/landing-page.component.html
  frontend/src/app/modules/auth/landing-page/landing-page.component.sass
  frontend/src/app/modules/main/main-menu/main-menu.component.html
  frontend/src/app/modules/main/main-menu/main-menu.component.sass
Labels: enhancement

#85 Added logo to assets
  frontend/src/assets/Logo.png
Labels: bug

#79 fix access to private resources; fix links
  backend/Perflow/Controllers/AlbumReactionController.cs
  backend/Perflow/Controllers/AlbumsController.cs
  backend/Perflow/Controllers/ArtistReactionController.cs
  backend/Perflow/Controllers/ArtistsController.cs
  backend/Perflow/Controllers/GroupsController.cs
  backend/Perflow/Controllers/PlaylistReactionController.cs
  backend/Perflow/Controllers/PlaylistsController.cs
  backend/Perflow/Controllers/SongReactionController.cs
  frontend/src/app/modules/main/cards/artist-card/artist-card.component.html
  frontend/src/app/modules/main/cards/new-release-card/new-release-card/new-release-card.component.html
  frontend/src/app/modules/main/cards/new-release-card/new-release-card/new-release-card.component.ts
Labels: bug

#84 Upload songs in album
  backend/Perflow/Controllers/SongsController.cs
  backend/Perflow/Services/Implementations/AlbumsService.cs
  backend/Perflow/Services/Implementations/SongsService.cs
  backend/Perflow/Services/Interfaces/ISongsService.cs
  frontend/src/app/helpers/AudioFileDuration.ts
  frontend/src/app/modules/album/album.module.ts
  frontend/src/app/modules/album/components/create-edit-album/create-edit-album/create-edit-album.component.html
  frontend/src/app/modules/album/components/create-edit-album/create-edit-album/create-edit-album.component.sass
  frontend/src/app/modules/album/components/create-edit-album/create-edit-album/create-edit-album.component.ts
  frontend/src/app/modules/album/components/create-edit-album/songs-upload-modal/songs-upload-modal.component.html
  frontend/src/app/modules/album/components/create-edit-album/songs-upload-modal/songs-upload-modal.component.sass
  frontend/src/app/modules/album/components/create-edit-album/songs-upload-modal/songs-upload-modal.component.spec.ts
  frontend/src/app/modules/album/components/create-edit-album/songs-upload-modal/songs-upload-modal.component.ts
  frontend/src/app/modules/shared/song-row/song-row.component.ts
  frontend/src/app/modules/shared/upload/song-image/song-image.component.html
  frontend/src/app/modules/shared/upload/song-image/song-image.component.sass
  frontend/src/app/modules/shared/upload/song-image/song-image.component.ts
  frontend/src/app/services/songs/songs.service.ts
Labels: enhancement, important

#86 Feature/page for playlist
  frontend/src/app/modules/main/main-menu/main-menu.component.html
  frontend/src/app/modules/main/main-menu/main-menu.component.sass
  frontend/src/app/modules/main/main-menu/main-menu.component.ts
  frontend/src/app/modules/main/main-routing.module.ts
  frontend/src/app/modules/main/main.module.ts
  frontend/src/app/modules/main/playlist/all/all.component.html
  frontend/src/app/modules/main/playlist/all/all.component.sass
  frontend/src/app/modules/main/playlists-all/all-playlists.component.html
  frontend/src/app/modules/main/playlists-all/all-playlists.component.sass
  frontend/src/app/modules/main/playlists-all/all-playlists.component.ts
  frontend/src/app/modules/main/view-playlist/view-playlist.component.html
  frontend/src/app/modules/main/view-playlist/view-playlist.component.sass
  frontend/src/app/modules/main/view-playlist/view-playlist.component.spec.ts
  frontend/src/app/modules/main/view-playlist/view-playlist.component.ts
  frontend/src/assets/images/view-playlists.png
Labels: enhancement

#87 Hotfix/route
  backend/ApiGateway/ApiGateway/configuration.Development.json
  backend/ApiGateway/ApiGateway/configuration.Production.json
Labels: bug

#88 Bugfix/fix group name display
  frontend/src/app/helpers/sort-compare-functions.ts
  frontend/src/app/models/song/song.ts
  frontend/src/app/modules/shared/song-row/song-row.component.html
  frontend/src/app/modules/shared/song-row/song-row.component.ts
Labels: bug

#92 Bugfix/moving img view playlist and error maybe null
  frontend/src/app/modules/main/view-playlist/view-playlist.component.html
  frontend/src/app/modules/main/view-playlist/view-playlist.component.sass
  frontend/src/app/modules/main/view-playlist/view-playlist.component.ts
Labels: bug

#91 add ability to like a playlist/song
  backend/Perflow/Common/DTO/Playlists/PlaylistDTO.cs
  backend/Perflow/Common/DTO/Reactions/NewPlaylistReactionDTO.cs
  backend/Perflow/Controllers/PlaylistReactionController.cs
  backend/Perflow/Controllers/PlaylistsController.cs
  backend/Perflow/Services/Implementations/PlaylistReactionService.cs
  backend/Perflow/Services/Implementations/PlaylistService.cs
  frontend/src/app/models/playlist/playlist.ts
  frontend/src/app/modules/main/cards/square-info-card/square-info-card.component.html
  frontend/src/app/modules/main/cards/square-info-card/square-info-card.component.ts
  frontend/src/app/modules/main/playlist/all/all.component.html
  frontend/src/app/modules/main/view-playlist/view-playlist.component.html
  frontend/src/app/modules/main/view-playlist/view-playlist.component.sass
  frontend/src/app/modules/main/view-playlist/view-playlist.component.ts
  frontend/src/app/modules/shared/playlist/search-song-row/search-song-row.component.sass
  frontend/src/app/modules/shared/song-row/song-row.component.ts
  frontend/src/app/modules/shared/song-toolbar/song-toolbar.component.html
  frontend/src/app/modules/shared/song-toolbar/song-toolbar.component.sass
  frontend/src/app/services/reaction.service.ts
Labels: enhancement

#89 Use connection string from configuration
  backend/Shared/Shared/AzureBlobStorage/Services/BlobService.cs
Labels: bug

#93 Added delete playlist item into menu
  frontend/src/app/modules/main/view-playlist/view-playlist.component.html
Labels: enhancement

#90 Bugfix/remove artist group selector
  backend/Perflow/Services/Implementations/AlbumsService.cs
  frontend/src/app/modules/album/components/create-edit-album/create-edit-album/create-edit-album.component.ts
  frontend/src/app/modules/album/components/create-edit-album/edit-album-modal/edit-album-modal.component.html
  frontend/src/app/modules/album/components/create-edit-album/edit-album-modal/edit-album-modal.component.sass
  frontend/src/app/modules/album/components/create-edit-album/edit-album-modal/edit-album-modal.component.ts
Labels: bug

#98 update ocelot routes
  backend/ApiGateway/ApiGateway/configuration.Development.json
  backend/ApiGateway/ApiGateway/configuration.Production.json
Labels: bug

#100 Fix layout bugs
  frontend/src/app/modules/auth/landing-page/landing-page.component.html
  frontend/src/app/modules/auth/landing-page/landing-page.component.sass
  frontend/src/app/modules/main/cards/circle-info-card/circle-info-card.component.html
  frontend/src/app/modules/main/cards/circle-info-card/circle-info-card.component.sass
  frontend/src/app/modules/main/cards/new-release-card/new-release-card/new-release-card.component.html
  frontend/src/app/modules/main/cards/new-release-card/new-release-card/new-release-card.component.sass
  frontend/src/app/modules/main/cards/playlist-card-styles.sass
  frontend/src/app/modules/main/main-home/main-home.component.html
  frontend/src/app/modules/main/main-home/main-home.component.sass
  frontend/src/app/modules/main/main-menu/main-menu.component.html
  frontend/src/app/modules/main/main-menu/main-menu.component.sass
  frontend/src/app/modules/main/profile-menu/profile-menu.component.sass
  frontend/src/app/modules/perflow-studio/left-side-menu/left-side-menu.component.html
  frontend/src/app/modules/perflow-studio/left-side-menu/left-side-menu.component.sass
Labels: bug

#95 Songtoolbar is showed always
  frontend/src/app/modules/main/main-menu/main-menu.component.sass
  frontend/src/app/modules/main/playlist/playlist.component.sass
  frontend/src/app/modules/shared/song-row/song-row.component.ts
  frontend/src/app/modules/shared/song-toolbar/song-toolbar.component.html
Labels: bug

#99 Added default playlist image on when create playlist
  frontend/src/app/modules/main/create-edit-playlist/create-edit-playlist/create-edit-playlist.component.ts
  frontend/src/assets/images/playlist_default.jpg
Labels: enhancement

#101 Fix cards height in playlist/all
  frontend/src/app/modules/main/cards/square-info-card/square-info-card.component.html
  frontend/src/app/modules/main/cards/square-info-card/square-info-card.component.sass
  frontend/src/app/modules/main/playlist/all/all.component.sass
Labels: bug

#103 Fix height in playlists/all page
  frontend/src/app/modules/main/playlist/all/all.component.sass
  frontend/src/app/modules/main/playlist/playlist.component.sass
Labels: bug

#102 Mobile add auth
  mobile/.gitignore
  mobile/analysis_options.yaml
  mobile/android/app/build.gradle
  mobile/android/app/src/main/AndroidManifest.xml
  mobile/android/build.gradle
  mobile/android/gradle/wrapper/gradle-wrapper.properties
  mobile/android/settings_aar.gradle
  mobile/lib/api_urls.dart
  mobile/lib/configure_services.config.dart
  mobile/lib/cubits/auth/auth_cubit.dart
  mobile/lib/cubits/auth/auth_cubit.freezed.dart
  mobile/lib/cubits/auth/auth_state.dart
  mobile/lib/cubits/main_navigation/main_navigation_cubit.dart
  mobile/lib/cubits/main_navigation/main_navigation_cubit.freezed.dart
  mobile/lib/cubits/main_navigation/main_navigation_state.dart
  mobile/lib/helpers/create_material_color.dart
  mobile/lib/helpers/dev_http_overrides.dart
  mobile/lib/helpers/http_methods.dart
  mobile/lib/helpers/validators/auth_validators.dart
  mobile/lib/main.dart
  mobile/lib/models/auth/auth_user.dart
  mobile/lib/models/auth/login_data.dart
  mobile/lib/models/auth/login_data.g.dart
  mobile/lib/models/auth/register_data.dart
  mobile/lib/models/auth/register_data.g.dart
  mobile/lib/models/enums/user_role.dart
  mobile/lib/perflow_app.dart
  mobile/lib/routes.dart
  mobile/lib/routes/auth_routes.dart
  mobile/lib/routes/guards/delete_when_needed
  mobile/lib/routes/main_routes.dart
  mobile/lib/routes/root_routes.dart
  mobile/lib/screens/auth/auth_screen.dart
  mobile/lib/screens/auth/login_form.dart
  mobile/lib/screens/auth/register_form.dart
  mobile/lib/screens/empty_screen.dart
  mobile/lib/screens/main/home/home_screen.dart
  mobile/lib/screens/main/library/library_screen.dart
  mobile/lib/screens/main/main_screen.dart
  mobile/lib/screens/main/search/search_screen.dart
  mobile/lib/screens/playlists/playlists_screen.dart
  mobile/lib/services/auth/auth_api.chopper.dart
  mobile/lib/services/auth/auth_api.dart
  mobile/lib/services/auth/auth_interceptor.dart
  mobile/lib/services/auth/auth_service.dart
  mobile/lib/services/chopper/chopper_service.dart
  mobile/lib/services/playback/playback_service.dart
  mobile/lib/services/playback_service.dart
  mobile/lib/services/songs/songs_api.chopper.dart
  mobile/lib/services/songs/songs_api.dart
  mobile/lib/services/songs/songs_service.dart
  mobile/lib/theme.dart
  mobile/lib/widgets/delete_when_needed
  mobile/lib/widgets/perflow_elevated_button.dart
  mobile/lib/widgets/perflow_outlined_button.dart
  mobile/pubspec.lock
  mobile/pubspec.yaml
Labels: enhancement

#94 Add WriteLine's for each step of upload
  backend/Shared/Shared/AzureBlobStorage/Services/BlobService.cs
Labels: bug

#105 Hotfix/get created refactoring
  backend/Perflow/Controllers/PlaylistsController.cs
  backend/Perflow/Services/Implementations/PlaylistService.cs
Labels: bug

#106 Get connection string by key from dictionary
  backend/Perflow/Startup.cs
  backend/Shared/Shared/AzureBlobStorage/Services/BlobService.cs
Labels: bug

#107 Rollback upload method back to startup usage
  backend/Perflow/Controllers/SongsController.cs
  backend/Perflow/Services/Implementations/SongsService.cs
  backend/Shared/Shared/AzureBlobStorage/Services/BlobService.cs
Labels: bug

#108 Hotfix/get created refactoring
  backend/Perflow/Common/DTO/Playlists/PlaylistNameDTO.cs
  backend/Perflow/Common/MappingProfiles/PlaylistProfile.cs
  backend/Perflow/Controllers/PlaylistsController.cs
  backend/Perflow/Services/Implementations/PlaylistService.cs
  frontend/src/app/models/playlist/playlist-name.ts
  frontend/src/app/modules/main/main-menu/main-menu.component.ts
  frontend/src/app/services/playlists/playlist.service.ts
Labels: bug

#109 Remove temporary song link
  frontend/src/app/modules/shared/mock-audio/links.ts
  frontend/src/app/modules/shared/song-row/song-row.component.ts
Labels: bug

#104 navigate to create/edit album-page
  frontend/src/app/modules/main/albums/albums.component.html
  frontend/src/app/modules/main/albums/albums.component.sass
  frontend/src/app/modules/main/albums/albums.component.spec.ts
  frontend/src/app/modules/main/albums/albums.component.ts
  frontend/src/app/modules/main/artists/artists.component.html
  frontend/src/app/modules/main/artists/artists.component.sass
  frontend/src/app/modules/main/artists/artists.component.spec.ts
  frontend/src/app/modules/main/artists/artists.component.ts
  frontend/src/app/modules/main/cards/album-card/album-card.component.html
  frontend/src/app/modules/main/cards/album-card/album-card.component.sass
  frontend/src/app/modules/main/playlist/album-list/album-list.component.html
  frontend/src/app/modules/main/playlist/album-list/album-list.component.sass
Labels: enhancement

#110 fix double scroll
  backend/Perflow/Controllers/PlaylistReactionController.cs
  backend/Perflow/Services/Implementations/PlaylistReactionService.cs
  frontend/src/app/modules/album/components/album-details/album-details.component.sass
  frontend/src/app/modules/artist/components/artist-details/artist-details.component.sass
  frontend/src/app/modules/artist/components/playlist-card/playlist-card.component.html
  frontend/src/app/modules/main/user-profile/user-profile.component.sass
  frontend/src/app/modules/user/user-profile-edit/user-profile-edit.component.sass
Labels: bug

#97 Feature/image cropper
  backend/Perflow/Perflow.csproj
  frontend/package.json
  frontend/src/app/app.module.ts
  frontend/src/app/models/shared/cropped.model.ts
  frontend/src/app/modules/main/create-edit-playlist/edit-playlist-modal/edit-playlist-modal.component.html
  frontend/src/app/modules/main/create-edit-playlist/edit-playlist-modal/edit-playlist-modal.component.ts
  frontend/src/app/modules/main/main.module.ts
  frontend/src/app/modules/shared/crop-image/crop-image.component.html
  frontend/src/app/modules/shared/crop-image/crop-image.component.sass
  frontend/src/app/modules/shared/crop-image/crop-image.component.spec.ts
  frontend/src/app/modules/shared/crop-image/crop-image.component.ts
  frontend/src/app/modules/shared/shared.module.ts
  frontend/src/environments/environment.ts
Labels: enhancement

#111 Play button does nothing instead of opening album
  frontend/src/app/modules/main/cards/circle-info-card/circle-info-card.component.html
  frontend/src/app/modules/main/cards/circle-info-card/circle-info-card.component.sass
  frontend/src/app/modules/main/cards/circle-info-card/circle-info-card.component.ts
Labels: bug

#113 Bugfix/load userinfo when it's needed
  backend/Perflow/Controllers/UsersController.cs
  backend/Perflow/Services/Implementations/UsersService.cs
  backend/Perflow/Services/Interfaces/IUsersService.cs
  frontend/src/app/modules/main/cards/circle-info-card/circle-info-card.component.ts
  frontend/src/app/modules/main/profile-menu/profile-menu.component.ts
  frontend/src/app/services/user.service.ts
  frontend/src/environments/environment.ts
Labels: bug

#114 Albums is displayed by current artist
  frontend/src/app/modules/main/cards/album-card/album-card.component.html
  frontend/src/app/modules/main/cards/album-card/album-card.component.sass
  frontend/src/app/modules/main/cards/album-card/album-card.component.ts
  frontend/src/app/modules/main/cards/playlist-card-styles.sass
  frontend/src/app/modules/perflow-studio/albums-page/albums-page.component.html
  frontend/src/app/modules/perflow-studio/albums-page/albums-page.component.ts
Labels: bug, enhancement

#115 Bugfix/no filtration in api playlists and too much data in response
  backend/ApiGateway/ApiGateway/configuration.Development.json
  backend/ApiGateway/ApiGateway/configuration.Production.json
  backend/Perflow/Controllers/PlaylistsController.cs
  backend/Perflow/Services/Implementations/PlaylistService.cs
  frontend/src/app/modules/main/cards/circle-info-card/circle-info-card.component.ts
  frontend/src/app/modules/main/playlist/playlist.component.ts
Labels: bug

#118 Fixed bug: api/Playlists/{id} loads extra info about author
  backend/Perflow/Common/DTO/Playlists/PlaylistDTO.cs
  backend/Perflow/Common/DTO/Users/UserForPlaylistDTO.cs
  backend/Perflow/Common/MappingProfiles/UserProfile.cs
  backend/Perflow/Services/Implementations/PlaylistService.cs
Labels: bug

#117 Like/dislike songs from toolbar
  backend/Perflow/Controllers/SongsController.cs
  backend/Perflow/Services/Implementations/SongsService.cs
  backend/Perflow/Services/Interfaces/ISongsService.cs
  frontend/src/app/models/song/song-info.ts
  frontend/src/app/modules/shared/song-row/song-row.component.ts
  frontend/src/app/modules/shared/song-toolbar/song-toolbar.component.html
  frontend/src/app/modules/shared/song-toolbar/song-toolbar.component.ts
  frontend/src/app/services/songs/songs.service.ts
Labels: enhancement

#96 Load top 20 by likes artists/songs in user profile
  backend/ApiGateway/ApiGateway/configuration.Development.json
  backend/ApiGateway/ApiGateway/configuration.Production.json
  backend/Perflow/Controllers/ArtistsController.cs
  backend/Perflow/Controllers/SongsController.cs
  backend/Perflow/Services/Implementations/ArtistService.cs
  backend/Perflow/Services/Implementations/SongsService.cs
  backend/Perflow/Services/Interfaces/IArtistService.cs
  backend/Perflow/Services/Interfaces/ISongsService.cs
  frontend/src/app/modules/main/user-profile/user-profile.component.html
  frontend/src/app/modules/main/user-profile/user-profile.component.sass
  frontend/src/app/modules/main/user-profile/user-profile.component.ts
  frontend/src/app/services/artists/artist.service.ts
  frontend/src/app/services/songs/songs.service.ts
Labels: enhancement

#119 Fixed bug: api/Playlists/songs/{id} loads too much data
  backend/Perflow/Common/DTO/Albums/AlbumForPlaylistDTO.cs
  backend/Perflow/Common/DTO/Groups/GroupForPlaylistDTO.cs
  backend/Perflow/Common/DTO/Songs/SongForPlaylistDTO.cs
  backend/Perflow/Common/DTO/Users/UserForPlaylistDTO.cs
  backend/Perflow/Common/MappingProfiles/AlbumProfile.cs
  backend/Perflow/Common/MappingProfiles/GroupProfile.cs
  backend/Perflow/Services/Implementations/PlaylistService.cs
Labels: bug

#116 Bugfix/edit liked songs requests
  backend/Perflow/Common/DTO/Albums/AlbumForListDTO.cs
  backend/Perflow/Common/DTO/Albums/AlbumViewDTO.cs
  backend/Perflow/Controllers/SongsController.cs
  backend/Perflow/Services/Implementations/AlbumReactionService.cs
  backend/Perflow/Services/Implementations/AlbumsService.cs
  backend/Perflow/Services/Implementations/SongsService.cs
  backend/Perflow/Services/Interfaces/ISongsService.cs
  frontend/src/app/models/album/album-name.ts
  frontend/src/app/models/album/albumForReadDTO.ts
  frontend/src/app/models/album/new-release-view.ts
  frontend/src/app/modules/main/cards/album-card/album-card.component.html
  frontend/src/app/modules/main/main-home/main-home.component.ts
  frontend/src/app/modules/main/playlist/all/all.component.ts
  frontend/src/app/modules/perflow-studio/albums-page/albums-page.component.ts
  frontend/src/app/services/album.service.ts
  frontend/src/app/services/songs/songs.service.ts
Labels: bug

#121 Update username in fb from db while logining
  backend/Perflow/Services/Implementations/AuthService.cs
Labels: bug, enhancement

#122 Fixed bug api/songs/search loads too much data
  backend/Perflow/Common/DTO/Albums/AlbumForPlaylistSongSearchDTO.cs
  backend/Perflow/Common/DTO/Songs/SongForPlaylistSongSearchDTO.cs
  backend/Perflow/Common/MappingProfiles/AlbumProfile.cs
  backend/Perflow/Common/MappingProfiles/SongProfile.cs
  backend/Perflow/Controllers/PlaylistsController.cs
  backend/Perflow/Controllers/SongsController.cs
  backend/Perflow/Services/Implementations/PlaylistService.cs
  backend/Perflow/Services/Implementations/SongsService.cs
  backend/Perflow/Services/Interfaces/ISongsService.cs
Labels: bug

#123 Create/edit playlist showing w/o reloading page
  frontend/src/app/modules/main/create-edit-playlist/create-edit-playlist/create-edit-playlist.component.ts
  frontend/src/app/modules/main/main-menu/main-menu.component.ts
  frontend/src/app/modules/shared/playlist/create-playlist/create-playlist.service.ts
Labels: bug

#124 Add uid initialization
  backend/Perflow/Services/Implementations/AuthService.cs
Labels: bug

#120 Add loading profile picture from google
  backend/Perflow/Services/Implementations/AuthService.cs
Labels: enhancement

#125 Add Audio Player
  mobile/android/app/src/main/AndroidManifest.xml
  mobile/android/app/src/profile/AndroidManifest.xml
  mobile/lib/api_urls.dart
  mobile/lib/configure_services.config.dart
  mobile/lib/cubits/auth/auth_cubit.dart
  mobile/lib/cubits/playback/playback_cubit.dart
  mobile/lib/cubits/playback/playback_cubit.freezed.dart
  mobile/lib/cubits/playback/playback_state.dart
  mobile/lib/cubits/playback/playback_status/playback_status_cubit.dart
  mobile/lib/cubits/playback/playback_status/playback_status_cubit.freezed.dart
  mobile/lib/cubits/playback/playback_status/playback_status_state.dart
  mobile/lib/main.dart
  mobile/lib/models/albums/album_simplified.dart
  mobile/lib/models/albums/album_simplified.g.dart
  mobile/lib/models/artists/artist_simplified.dart
  mobile/lib/models/artists/artist_simplified.g.dart
  mobile/lib/models/playback/playback_time.dart
  mobile/lib/models/songs/song.dart
  mobile/lib/models/songs/song.g.dart
  mobile/lib/routes/main_routes.dart
  mobile/lib/screens/main/home/home_screen.dart
  mobile/lib/screens/main/main_screen.dart
  mobile/lib/services/auth/auth_service.dart
  mobile/lib/services/playback/playback_handler.dart
  mobile/lib/services/playback/playback_service.dart
  mobile/lib/theme.dart
  mobile/lib/widgets/player/player.dart
  mobile/pubspec.lock
  mobile/pubspec.yaml
Labels: enhancement

#126 Fixed bug: different dropdowns on different pages
  frontend/src/app/modules/main/profile-menu/profile-menu.component.html
  frontend/src/app/modules/main/profile-menu/profile-menu.component.sass
  frontend/src/app/modules/main/profile-menu/profile-menu.component.ts
  frontend/src/app/modules/main/view-playlist/view-playlist.component.html
  frontend/src/app/modules/main/view-playlist/view-playlist.component.sass
Labels: bug

#127 Highlight menu points
  frontend/src/app/modules/main/main-menu/main-menu.component.html
  frontend/src/app/modules/main/main-menu/main-menu.component.sass
Labels: enhancement, Refactoring

#129 Added ability to delete playlist
  backend/Perflow/DataAccess/Context/EntityTypeConfigurations/PlaylistReactionConfiguration.cs
  backend/Perflow/Migrations/20210816214309_ChangePlaylistReactionDeleteBehaviorToCascade.Designer.cs
  backend/Perflow/Migrations/20210816214309_ChangePlaylistReactionDeleteBehaviorToCascade.cs
  backend/Perflow/Migrations/PerflowContextModelSnapshot.cs
  backend/Perflow/Services/Implementations/PlaylistService.cs
  frontend/src/app/modules/main/create-edit-playlist/create-edit-playlist/create-edit-playlist.component.ts
  frontend/src/app/modules/main/main-menu/main-menu.component.ts
  frontend/src/app/modules/main/view-playlist/view-playlist.component.html
  frontend/src/app/modules/main/view-playlist/view-playlist.component.ts
  frontend/src/app/modules/shared/playlist/create-playlist/create-playlist.service.ts
Labels: enhancement

#130 Split ocelot configuration into multiple files
  backend/ApiGateway/.gitignore
  backend/ApiGateway/ApiGateway/Configuration/Development/albumReaction.json
  backend/ApiGateway/ApiGateway/Configuration/Development/albums.json
  backend/ApiGateway/ApiGateway/Configuration/Development/artistReaction.json
  backend/ApiGateway/ApiGateway/Configuration/Development/artists.json
  backend/ApiGateway/ApiGateway/Configuration/Development/auth.json
  backend/ApiGateway/ApiGateway/Configuration/Development/files.json
  backend/ApiGateway/ApiGateway/Configuration/Development/global.json
  backend/ApiGateway/ApiGateway/Configuration/Development/groups.json
  backend/ApiGateway/ApiGateway/Configuration/Development/playlistReaction.json
  backend/ApiGateway/ApiGateway/Configuration/Development/playlists.json
  backend/ApiGateway/ApiGateway/Configuration/Development/songReaction.json
  backend/ApiGateway/ApiGateway/Configuration/Development/songs.json
  backend/ApiGateway/ApiGateway/Configuration/Development/studio.songs.json
  backend/ApiGateway/ApiGateway/Configuration/Development/users.json
  backend/ApiGateway/ApiGateway/Configuration/Production/albumReaction.json
  backend/ApiGateway/ApiGateway/Configuration/Production/albums.json
  backend/ApiGateway/ApiGateway/Configuration/Production/artistReaction.json
  backend/ApiGateway/ApiGateway/Configuration/Production/artists.json
  backend/ApiGateway/ApiGateway/Configuration/Production/auth.json
  backend/ApiGateway/ApiGateway/Configuration/Production/files.json
  backend/ApiGateway/ApiGateway/Configuration/Production/global.json
  backend/ApiGateway/ApiGateway/Configuration/Production/groups.json
  backend/ApiGateway/ApiGateway/Configuration/Production/playlistReaction.json
  backend/ApiGateway/ApiGateway/Configuration/Production/playlists.json
  backend/ApiGateway/ApiGateway/Configuration/Production/songReaction.json
  backend/ApiGateway/ApiGateway/Configuration/Production/songs.json
  backend/ApiGateway/ApiGateway/Configuration/Production/studio.songs.json
  backend/ApiGateway/ApiGateway/Configuration/Production/users.json
  backend/ApiGateway/ApiGateway/Exceptions/OcelotConfigurationException.cs
  backend/ApiGateway/ApiGateway/Extensions/AddOcelotConfigurations.cs
  backend/ApiGateway/ApiGateway/Program.cs
  backend/ApiGateway/ApiGateway/configuration.Development.json
  backend/ApiGateway/ApiGateway/configuration.Production.json
Labels: enhancement

#128 Feature/save settings on backend
  backend/Perflow/Common/DTO/Users/UserChangeSettingsDTO.cs
  backend/Perflow/Common/MappingProfiles/UserSettingsProfile.cs
  backend/Perflow/Controllers/UsersController.cs
  backend/Perflow/DataAccess/Context/EntityTypeConfigurations/UserSettingsConfiguration.cs
  backend/Perflow/Domain/UserSettings.cs
  backend/Perflow/Services/Extensions/ServiceExtensions.cs
  backend/Perflow/Services/Implementations/UsersService.cs
  backend/Perflow/Services/Interfaces/IUsersService.cs
  frontend/src/app/models/enums/audio-quality.ts
  frontend/src/app/models/user/user-change-settings.ts
  frontend/src/app/models/user/user-settings.ts
  frontend/src/app/modules/main/settings/settings.component.html
  frontend/src/app/modules/main/settings/settings.component.ts
  frontend/src/app/services/user.service.ts
Labels: enhancement

#131 Add some routes to ocelot
  backend/ApiGateway/ApiGateway/Configuration/Development/songs.json
  backend/ApiGateway/ApiGateway/Configuration/Development/users.json
  backend/ApiGateway/ApiGateway/Configuration/Production/songs.json
  backend/ApiGateway/ApiGateway/Configuration/Production/users.json
Labels: bug

#132 Rename studio endpoints
  backend/ApiGateway/ApiGateway/Configuration/Development/studio.songs.json
  backend/ApiGateway/ApiGateway/Configuration/Production/studio.songs.json
  backend/Perflow.Studio/Controllers/SongsController.cs
Labels: bug

#138 delete songs after deleting album
  backend/Perflow/DataAccess/Context/EntityTypeConfigurations/SongConfiguration.cs
  backend/Perflow/DataAccess/Context/EntityTypeConfigurations/SongReactionConfiguration.cs
  backend/Perflow/Migrations/20210819054748_ChangeAlbumDeleteBehavior.Designer.cs
  backend/Perflow/Migrations/20210819054748_ChangeAlbumDeleteBehavior.cs
  backend/Perflow/Migrations/PerflowContextModelSnapshot.cs
Labels: bug

#136 Feature/like artist
  backend/Perflow/Common/DTO/Users/ArtistFullDTO.cs
  backend/Perflow/Common/MappingProfiles/UserProfile.cs
  backend/Perflow/Controllers/ArtistsController.cs
  backend/Perflow/DataAccess/Context/EntityTypeConfigurations/UserConfiguration.cs
  backend/Perflow/Domain/User.cs
  backend/Perflow/Services/Implementations/ArtistService.cs
  backend/Perflow/Services/Interfaces/IArtistService.cs
  frontend/src/app/models/user/artist-full.ts
  frontend/src/app/modules/artist/components/artist-details/artist-details.component.html
  frontend/src/app/modules/artist/components/artist-details/artist-details.component.ts
  frontend/src/app/services/artist.service.ts
Labels: enhancement

#134 bugfix/artists albums playlists absence message
  frontend/src/app/modules/main/playlist/album-list/album-list.component.html
  frontend/src/app/modules/main/playlist/all/all.component.html
  frontend/src/app/modules/main/playlist/all/all.component.sass
  frontend/src/app/modules/main/playlist/artist-list/artist-list.component.html
Labels: bug

#140 Not show 'Create playlist' button on my playlist
  frontend/src/app/modules/main/playlist/album-list/album-list.component.html
Labels: bug

#141 feature/add playlist coming soon
  frontend/src/app/modules/perflow-studio/playlists-page/playlists-page.component.html
  frontend/src/app/modules/perflow-studio/playlists-page/playlists-page.component.sass
Labels: enhancement

#145 Fix get requests after each reload
  frontend/src/app/modules/main/album-details/album-details.component.ts
  frontend/src/app/modules/main/playlist/all/all.component.html
Labels: bug

#144 Bugfix/fix high priority
  backend/Perflow/Services/Implementations/AlbumsService.cs
  backend/Perflow/Services/Implementations/UsersService.cs
  frontend/src/app/modules/main/cards/new-release-card/new-release-card/new-release-card.component.ts
  frontend/src/app/modules/main/view-playlist/view-playlist.component.html
  frontend/src/app/modules/main/view-playlist/view-playlist.component.sass
Labels: bug

#142 Created a search page
  backend/ApiGateway/ApiGateway/Configuration/Development/search.json
  backend/ApiGateway/ApiGateway/Configuration/Production/search.json
  backend/Perflow/Common/DTO/Search/SearchResultDTO.cs
  backend/Perflow/Common/MappingProfiles/UserProfile.cs
  backend/Perflow/Controllers/SearchController.cs
  backend/Perflow/Services/Extensions/ServiceExtensions.cs
  backend/Perflow/Services/Implementations/SearchService.cs
  frontend/src/app/models/search/found-data.ts
  frontend/src/app/models/search/search-param.ts
  frontend/src/app/modules/main/cards/playlist-card/playlist-card.component.sass
  frontend/src/app/modules/main/main-routing.module.ts
  frontend/src/app/modules/main/main.module.ts
  frontend/src/app/modules/main/search/components/search-albums-result/search-albums-result.component.html
  frontend/src/app/modules/main/search/components/search-albums-result/search-albums-result.component.sass
  frontend/src/app/modules/main/search/components/search-albums-result/search-albums-result.component.spec.ts
  frontend/src/app/modules/main/search/components/search-albums-result/search-albums-result.component.ts
  frontend/src/app/modules/main/search/components/search-artists-result/search-artists-result.component.html
  frontend/src/app/modules/main/search/components/search-artists-result/search-artists-result.component.sass
  frontend/src/app/modules/main/search/components/search-artists-result/search-artists-result.component.spec.ts
  frontend/src/app/modules/main/search/components/search-artists-result/search-artists-result.component.ts
  frontend/src/app/modules/main/search/components/search-playlists-result/search-playlists-result.component.html
  frontend/src/app/modules/main/search/components/search-playlists-result/search-playlists-result.component.sass
  frontend/src/app/modules/main/search/components/search-playlists-result/search-playlists-result.component.spec.ts
  frontend/src/app/modules/main/search/components/search-playlists-result/search-playlists-result.component.ts
  frontend/src/app/modules/main/search/components/search-result-styles.sass
  frontend/src/app/modules/main/search/components/search-songs-result/search-songs-result.component.html
  frontend/src/app/modules/main/search/components/search-songs-result/search-songs-result.component.sass
  frontend/src/app/modules/main/search/components/search-songs-result/search-songs-result.component.spec.ts
  frontend/src/app/modules/main/search/components/search-songs-result/search-songs-result.component.ts
  frontend/src/app/modules/main/search/search.component.html
  frontend/src/app/modules/main/search/search.component.sass
  frontend/src/app/modules/main/search/search.component.ts
  frontend/src/app/modules/shared/playlist/search-song-row/search-song-row.component.sass
  frontend/src/app/services/search.service.ts
  frontend/src/app/services/songs/songs.service.ts
Labels: enhancement

#146 Implement recently played logic
  backend/ApiGateway/ApiGateway/Configuration/Development/recentlyPlayed.json
  backend/ApiGateway/ApiGateway/Configuration/Production/recentlyPlayed.json
  backend/Perflow/Common/DTO/RecentlyPlayed/RPViaSongIdInfoDTO.cs
  backend/Perflow/Common/DTO/RecentlyPlayed/RecentlyPlayedDTO.cs
  backend/Perflow/Common/MappingProfiles/RecentlyPlayedProfile.cs
  backend/Perflow/Controllers/RecentlyPlayedController.cs
  backend/Perflow/DataAccess/Context/EntityTypeConfigurations/RecentlyPlayedConfiguration.cs
  backend/Perflow/DataAccess/Context/ModelBuilderExtensions.cs
  backend/Perflow/DataAccess/Context/PerflowContext.cs
  backend/Perflow/Domain/RecentlyPlayed.cs
  backend/Perflow/Migrations/20210820024853_RecentlyPlayed.Designer.cs
  backend/Perflow/Migrations/20210820024853_RecentlyPlayed.cs
  backend/Perflow/Migrations/PerflowContextModelSnapshot.cs
  backend/Perflow/Services/Extensions/ServiceExtensions.cs
  backend/Perflow/Services/Implementations/RecentlyPlayedService.cs
  frontend/src/app/models/recently-played/recently-played.ts
  frontend/src/app/models/recently-played/rp-via-song-id-info.ts
  frontend/src/app/modules/shared/song-toolbar/song-toolbar.component.ts
  frontend/src/app/services/recently-played.service.ts
Labels: enhancement

#135 Feature/share logic
  backend/Perflow/DataAccess/Context/EntityTypeConfigurations/UserSettingsConfiguration.cs
  backend/Perflow/Domain/UserSettings.cs
  backend/Perflow/Migrations/20210817124340_SetUserSettingsDefaultValues.Designer.cs
  backend/Perflow/Migrations/20210817124340_SetUserSettingsDefaultValues.cs
  backend/Perflow/Migrations/PerflowContextModelSnapshot.cs
  backend/Perflow/seed.sql
  frontend/src/app/modules/main/album-details/album-details.component.html
  frontend/src/app/modules/main/album-details/album-details.component.ts
  frontend/src/app/modules/main/artist-details/artist-details.component.html
  frontend/src/app/modules/main/artist-details/artist-details.component.sass
  frontend/src/app/modules/main/artist-details/artist-details.component.ts
  frontend/src/app/modules/main/create-edit-playlist/create-edit-playlist/create-edit-playlist.component.html
  frontend/src/app/modules/main/create-edit-playlist/create-edit-playlist/create-edit-playlist.component.sass
  frontend/src/app/modules/main/create-edit-playlist/create-edit-playlist/create-edit-playlist.component.ts
  frontend/src/app/modules/main/view-playlist/view-playlist.component.html
  frontend/src/app/modules/main/view-playlist/view-playlist.component.sass
  frontend/src/app/modules/main/view-playlist/view-playlist.component.ts
  frontend/src/app/modules/perflow-studio/create-edit-album/create-edit-album/create-edit-album.component.html
  frontend/src/app/modules/perflow-studio/create-edit-album/create-edit-album/create-edit-album.component.sass
  frontend/src/app/modules/perflow-studio/create-edit-album/create-edit-album/create-edit-album.component.ts
  frontend/src/app/modules/shared/song-row/song-row.component.html
  frontend/src/app/modules/shared/song-row/song-row.component.sass
  frontend/src/app/modules/shared/song-row/song-row.component.ts
  frontend/src/styles.sass
Labels: enhancement

#147 Song edit on album edit page
  backend/Perflow/Common/DTO/Songs/SongForPlaylistDTO.cs
  backend/Perflow/Common/DTO/Songs/SongOrderDTO.cs
  backend/Perflow/Common/DTO/Songs/SongReadDTO.cs
  backend/Perflow/Common/DTO/Songs/SongWriteDTO.cs
  backend/Perflow/Controllers/SongsController.cs
  backend/Perflow/Domain/Song.cs
  backend/Perflow/Migrations/20210820081537_AddOrderToSong.Designer.cs
  backend/Perflow/Migrations/20210820081537_AddOrderToSong.cs
  backend/Perflow/Migrations/PerflowContextModelSnapshot.cs
  backend/Perflow/Services/Implementations/AlbumsService.cs
  backend/Perflow/Services/Implementations/SongsService.cs
  backend/Perflow/Services/Interfaces/ISongsService.cs
  frontend/src/app/models/song/song-order.ts
  frontend/src/app/modules/perflow-studio/create-edit-album/create-edit-album/create-edit-album.component.html
  frontend/src/app/modules/shared/shared.module.ts
  frontend/src/app/modules/shared/song-row/song-row.component.html
  frontend/src/app/modules/shared/song-row/song-row.component.sass
  frontend/src/app/modules/shared/song-row/song-row.component.ts
  frontend/src/app/modules/shared/songs-list/songs-list.component.html
  frontend/src/app/modules/shared/songs-list/songs-list.component.sass
  frontend/src/app/modules/shared/songs-list/songs-list.component.ts
  frontend/src/app/services/songs/songs.service.ts
Labels: enhancement

#143 Song queue ヽ(*・ω・)ﾉ
  backend/ApiGateway/ApiGateway/Configuration/Development/albums.json
  backend/ApiGateway/ApiGateway/Configuration/Production/albums.json
  backend/Perflow/Common/DTO/Albums/AlbumForPlaylistDTO.cs
  backend/Perflow/Common/MappingProfiles/UserProfile.cs
  backend/Perflow/Controllers/AlbumsController.cs
  backend/Perflow/Services/Implementations/AlbumReactionService.cs
  backend/Perflow/Services/Implementations/AlbumsService.cs
  frontend/src/app/models/album/albumForReadDTO.ts
  frontend/src/app/modules/main/album-details/album-details.component.html
  frontend/src/app/modules/main/album-details/album-details.component.ts
  frontend/src/app/modules/main/artist-details/artist-details.component.html
  frontend/src/app/modules/main/artist-details/artist-details.component.ts
  frontend/src/app/modules/main/cards/album-card/album-card.component.html
  frontend/src/app/modules/main/main-menu-profile/main-menu-profile.component.html
  frontend/src/app/modules/main/main-menu-profile/main-menu-profile.component.ts
  frontend/src/app/modules/main/main-menu/main-menu.component.html
  frontend/src/app/modules/main/main-menu/main-menu.component.sass
  frontend/src/app/modules/main/main-menu/main-menu.component.ts
  frontend/src/app/modules/main/view-playlist/view-playlist.component.html
  frontend/src/app/modules/main/view-playlist/view-playlist.component.ts
  frontend/src/app/modules/perflow-studio/albums-page/albums-page.component.ts
  frontend/src/app/modules/shared/playing/playing.component.html
  frontend/src/app/modules/shared/playing/playing.component.sass
  frontend/src/app/modules/shared/playing/playing.component.spec.ts
  frontend/src/app/modules/shared/playing/playing.component.ts
  frontend/src/app/modules/shared/queue/queue/queue.component.html
  frontend/src/app/modules/shared/queue/queue/queue.component.sass
  frontend/src/app/modules/shared/queue/queue/queue.component.spec.ts
  frontend/src/app/modules/shared/queue/queue/queue.component.ts
  frontend/src/app/modules/shared/shared.module.ts
  frontend/src/app/modules/shared/song-row/song-row.component.html
  frontend/src/app/modules/shared/song-row/song-row.component.sass
  frontend/src/app/modules/shared/song-row/song-row.component.ts
  frontend/src/app/modules/shared/song-toolbar/song-toolbar.component.html
  frontend/src/app/modules/shared/song-toolbar/song-toolbar.component.sass
  frontend/src/app/modules/shared/song-toolbar/song-toolbar.component.ts
  frontend/src/app/modules/shared/songs-list/songs-list.component.html
  frontend/src/app/modules/shared/songs-list/songs-list.component.ts
  frontend/src/app/services/queue.service.ts
  frontend/src/app/services/song-toolbar.service.ts
  frontend/src/styles.sass
Labels: enhancement

#148 Add routes to ocelot
  backend/ApiGateway/ApiGateway/Configuration/Development/songs.json
  backend/ApiGateway/ApiGateway/Configuration/Production/songs.json
Labels: bug

#149 Implemented search for songs artists albums playlists
  backend/ApiGateway/ApiGateway/Configuration/Development/songs.json
  backend/ApiGateway/ApiGateway/Configuration/Production/songs.json
  backend/Perflow/Controllers/SearchController.cs
  backend/Perflow/Controllers/SongsController.cs
  backend/Perflow/Services/Implementations/SearchService.cs
  backend/Perflow/Services/Implementations/SongsService.cs
  backend/Perflow/Services/Interfaces/ISongsService.cs
  frontend/package.json
  frontend/src/app/models/search/search-param.ts
  frontend/src/app/modules/main/cards/album-card/album-card.component.html
  frontend/src/app/modules/main/cards/album-card/album-card.component.sass
  frontend/src/app/modules/main/cards/artist-card/artist-card.component.html
  frontend/src/app/modules/main/cards/artist-card/artist-card.component.sass
  frontend/src/app/modules/main/cards/artist-card/artist-card.component.ts
  frontend/src/app/modules/main/cards/playlist-card/playlist-card.component.sass
  frontend/src/app/modules/main/create-edit-playlist/create-edit-playlist/create-edit-playlist.component.ts
  frontend/src/app/modules/main/main-routing.module.ts
  frontend/src/app/modules/main/main.module.ts
  frontend/src/app/modules/main/search/components/all-albums/all-albums.component.html
  frontend/src/app/modules/main/search/components/all-albums/all-albums.component.sass
  frontend/src/app/modules/main/search/components/all-albums/all-albums.component.spec.ts
  frontend/src/app/modules/main/search/components/all-albums/all-albums.component.ts
  frontend/src/app/modules/main/search/components/all-artists/all-artists.component.html
  frontend/src/app/modules/main/search/components/all-artists/all-artists.component.sass
  frontend/src/app/modules/main/search/components/all-artists/all-artists.component.spec.ts
  frontend/src/app/modules/main/search/components/all-artists/all-artists.component.ts
  frontend/src/app/modules/main/search/components/all-playlists/all-playlists.component.html
  frontend/src/app/modules/main/search/components/all-playlists/all-playlists.component.sass
  frontend/src/app/modules/main/search/components/all-playlists/all-playlists.component.spec.ts
  frontend/src/app/modules/main/search/components/all-playlists/all-playlists.component.ts
  frontend/src/app/modules/main/search/components/all-songs/all-songs.component.html
  frontend/src/app/modules/main/search/components/all-songs/all-songs.component.sass
  frontend/src/app/modules/main/search/components/all-songs/all-songs.component.spec.ts
  frontend/src/app/modules/main/search/components/all-songs/all-songs.component.ts
  frontend/src/app/modules/main/search/components/search-albums-result/search-albums-result.component.html
  frontend/src/app/modules/main/search/components/search-albums-result/search-albums-result.component.sass
  frontend/src/app/modules/main/search/components/search-albums-result/search-albums-result.component.ts
  frontend/src/app/modules/main/search/components/search-artists-result/search-artists-result.component.html
  frontend/src/app/modules/main/search/components/search-artists-result/search-artists-result.component.sass
  frontend/src/app/modules/main/search/components/search-artists-result/search-artists-result.component.ts
  frontend/src/app/modules/main/search/components/search-playlists-result/search-playlists-result.component.html
  frontend/src/app/modules/main/search/components/search-playlists-result/search-playlists-result.component.sass
  frontend/src/app/modules/main/search/components/search-playlists-result/search-playlists-result.component.ts
  frontend/src/app/modules/main/search/components/search-result-styles.sass
  frontend/src/app/modules/main/search/components/search-songs-result/search-songs-result.component.html
  frontend/src/app/modules/main/search/components/search-songs-result/search-songs-result.component.sass
  frontend/src/app/modules/main/search/components/search-songs-result/search-songs-result.component.ts
  frontend/src/app/modules/main/search/search.component.html
  frontend/src/app/modules/main/search/search.component.ts
  frontend/src/app/services/search.service.ts
  frontend/src/app/services/songs/songs.service.ts
Labels: enhancement

#150 fix images
  backend/Perflow/Common/MappingProfiles/PlaylistProfile.cs
  backend/Perflow/Common/MappingProfiles/UserProfile.cs
  backend/Perflow/Services/Implementations/AlbumsService.cs
  backend/Perflow/Services/Implementations/ArtistService.cs
  backend/Perflow/Services/Implementations/PlaylistService.cs
  backend/Perflow/Services/Implementations/SearchService.cs
  frontend/src/app/modules/main/cards/album-card/album-card.component.html
Labels: bug

#151 Fix song time on uploading
  backend/Perflow/Services/Implementations/AlbumsService.cs
  backend/Perflow/Services/Implementations/SongsService.cs
  frontend/src/app/helpers/AudioFileDuration.ts
  frontend/src/app/modules/shared/song-row/song-row.component.sass
Labels: bug

#154 Play/Pause on playing song in queue
  frontend/src/app/modules/main/main-menu-profile/main-menu-profile.component.html
  frontend/src/app/modules/main/main-menu-profile/main-menu-profile.component.ts
  frontend/src/app/modules/shared/queue/queue/queue.component.html
  frontend/src/app/modules/shared/queue/queue/queue.component.ts
  frontend/src/app/modules/shared/song-row/song-row.component.html
  frontend/src/app/modules/shared/song-row/song-row.component.sass
  frontend/src/app/modules/shared/song-row/song-row.component.ts
  frontend/src/app/modules/shared/song-toolbar/song-toolbar.component.ts
  frontend/src/app/modules/shared/songs-list/songs-list.component.html
  frontend/src/app/modules/shared/songs-list/songs-list.component.ts
Labels: bug

#156 Fix artists and albums grid
  frontend/src/app/modules/main/playlist/album-list/album-list.component.html
  frontend/src/app/modules/main/playlist/artist-list/artist-list.component.html
Labels: bug

#153 feature/song-settings-box
  frontend/src/app/modules/shared/song-row/song-row.component.html
Labels: enhancement

#152 Fixed bug in search logic
  frontend/src/app/modules/main/search/search.component.ts
Labels: bug

#157 Fixed font in dropdowns
  frontend/src/app/modules/main/create-edit-playlist/create-edit-playlist/create-edit-playlist.component.html
  frontend/src/app/modules/main/create-edit-playlist/create-edit-playlist/create-edit-playlist.component.sass
  frontend/src/app/modules/main/profile-menu/profile-menu.component.sass
  frontend/src/app/modules/main/user-profile/user-profile.component.html
  frontend/src/app/modules/main/user-profile/user-profile.component.sass
  frontend/src/app/modules/main/view-playlist/view-playlist.component.html
  frontend/src/app/modules/main/view-playlist/view-playlist.component.sass
Labels: bug

#158 Artist redirecting from "now playing" works properly
  frontend/src/app/helpers/AudioFileDuration.ts
  frontend/src/app/modules/main/artist-details/artist-details.component.ts
  frontend/src/app/modules/shared/queue/queue/queue.component.html
  frontend/src/app/modules/shared/queue/queue/queue.component.sass
Labels: bug

#161 fix edit button
  frontend/src/app/modules/main/cards/album-card/album-card.component.sass
Labels: bug

#155 update snackbar; fix layout
  backend/Perflow/Common/DTO/Albums/AlbumFullDTO.cs
  backend/Perflow/Common/DTO/Songs/SongForAlbumDTO.cs
  backend/Perflow/Common/MappingProfiles/AlbumProfile.cs
  backend/Perflow/Common/MappingProfiles/SongProfile.cs
  backend/Perflow/Services/Implementations/AlbumsService.cs
  frontend/src/app/models/common/snackbar-info.ts
  frontend/src/app/modules/auth/auth.module.ts
  frontend/src/app/modules/auth/landing-page/landing-page.component.html
  frontend/src/app/modules/auth/landing-page/landing-page.component.ts
  frontend/src/app/modules/main/album-details/album-details.component.html
  frontend/src/app/modules/main/album-details/album-details.component.sass
  frontend/src/app/modules/main/album-details/album-details.component.ts
  frontend/src/app/modules/main/artist-details/artist-details.component.sass
  frontend/src/app/modules/main/cards/new-release-card/new-release-card/new-release-card.component.html
  frontend/src/app/modules/main/cards/new-release-card/new-release-card/new-release-card.component.sass
  frontend/src/app/modules/main/cards/playlist-card/playlist-card.component.sass
  frontend/src/app/modules/main/cards/square-info-card/square-info-card.component.sass
  frontend/src/app/modules/main/create-edit-playlist/create-edit-playlist/create-edit-playlist.component.sass
  frontend/src/app/modules/main/main-menu-profile/main-menu-profile.component.html
  frontend/src/app/modules/main/songs/songs.component.sass
  frontend/src/app/modules/main/view-playlist/view-playlist.component.html
  frontend/src/app/modules/main/view-playlist/view-playlist.component.sass
  frontend/src/app/modules/main/view-playlist/view-playlist.component.ts
  frontend/src/app/modules/perflow-studio/create-edit-album/create-edit-album/create-edit-album.component.html
  frontend/src/app/modules/register/user-registration-page/user-registration-page.component.html
  frontend/src/app/modules/register/user-registration-page/user-registration-page.component.ts
  frontend/src/app/modules/shared/shared.module.ts
  frontend/src/app/modules/shared/snackbar/snackbar.component.html
  frontend/src/app/modules/shared/snackbar/snackbar.component.sass
  frontend/src/app/modules/shared/snackbar/snackbar.component.spec.ts
  frontend/src/app/modules/shared/snackbar/snackbar.component.ts
  frontend/src/app/modules/shared/song-toolbar/song-toolbar.component.sass
  frontend/src/app/modules/user/profile-edit-form/profile-edit-form.component.html
  frontend/src/app/modules/user/profile-edit-form/profile-edit-form.component.ts
  frontend/src/app/modules/user/update-password-form/update-password-form.component.html
  frontend/src/app/modules/user/update-password-form/update-password-form.component.ts
  frontend/src/app/modules/user/user-profile-edit/user-profile-edit.component.html
  frontend/src/app/modules/user/user-profile-edit/user-profile-edit.component.ts
  frontend/src/app/services/snackbar.service.ts
  frontend/src/styles.sass
Labels: bug

#163 Fixed icon recently played songs
  backend/Perflow/Services/Implementations/RecentlyPlayedService.cs
  frontend/src/app/modules/main/create-edit-playlist/edit-playlist-modal/edit-playlist-modal.component.sass
  frontend/src/app/modules/perflow-studio/create-edit-album/edit-album-modal/edit-album-modal.component.sass
Labels: bug

#165 Removed Lorem ipsum from the site
  backend/ApiGateway/ApiGateway/Configuration/Development/albums.json
  backend/ApiGateway/ApiGateway/Configuration/Production/albums.json
  backend/Perflow/Common/DTO/Albums/AlbumForNewestFiveDTO.cs
  backend/Perflow/Controllers/AlbumsController.cs
  backend/Perflow/Services/Implementations/AlbumsService.cs
  frontend/src/app/models/album/newest-five.ts
  frontend/src/app/modules/main/cards/circle-info-card/circle-info-card.component.sass
  frontend/src/app/modules/main/cards/song-card/song-card.component.sass
  frontend/src/app/modules/main/main-home/main-home.component.html
  frontend/src/app/modules/main/main-home/main-home.component.ts
  frontend/src/app/services/album.service.ts
Labels: bug, enhancement

#166 Image is displayed correctly
  frontend/src/app/services/queue.service.ts
Labels: bug

#159 Song is able to be deleted from queue
  frontend/src/app/modules/main/main-menu-profile/main-menu-profile.component.html
  frontend/src/app/modules/main/main-menu-profile/main-menu-profile.component.ts
  frontend/src/app/modules/shared/queue/queue/queue.component.html
  frontend/src/app/modules/shared/queue/queue/queue.component.ts
  frontend/src/app/modules/shared/song-toolbar/song-toolbar.component.ts
Labels: bug

#168 add ability to dislike a playlist (AllComponent)
  frontend/src/app/modules/main/cards/square-info-card/square-info-card.component.html
  frontend/src/app/modules/main/cards/square-info-card/square-info-card.component.sass
  frontend/src/app/modules/main/cards/square-info-card/square-info-card.component.ts
  frontend/src/app/modules/main/playlist/all/all.component.html
  frontend/src/app/modules/main/playlist/all/all.component.ts
Labels: enhancement

#169 fix liked artists
  frontend/src/app/modules/main/playlist/artist-list/artist-list.component.html
Labels: bug

#170 fix anotherAlbums links; update dropdown menu
  frontend/src/app/modules/main/album-details/album-details.component.html
  frontend/src/app/modules/main/album-details/album-details.component.ts
Labels: bug

#171 add default userIcon
  backend/Perflow/Services/Implementations/SearchService.cs
  frontend/src/app/modules/main/create-edit-playlist/create-edit-playlist/create-edit-playlist.component.sass
  frontend/src/app/modules/main/profile-menu/profile-menu.component.html
  frontend/src/app/modules/main/profile-menu/profile-menu.component.sass
Labels: bug

#173 Bugfix/fix UI bugs
  frontend/src/app/modules/main/album-details/album-details.component.sass
  frontend/src/app/modules/shared/queue/queue/queue.component.sass
  frontend/src/app/modules/shared/song-row/song-row.component.sass
Labels: bug

#172 Main. Recently played. Link should navigate to album.
  backend/Perflow/Services/Implementations/RecentlyPlayedService.cs
  frontend/src/app/modules/main/cards/song-card/song-card.component.html
  frontend/src/app/modules/main/cards/song-card/song-card.component.sass
  frontend/src/app/modules/main/cards/song-card/song-card.component.ts
  frontend/src/app/modules/main/main-home/main-home.component.html
Labels: bug

#174 Add player screen
  mobile/lib/configure_services.config.dart
  mobile/lib/cubits/main_navigation/main_navigation_cubit.dart
  mobile/lib/cubits/main_navigation/main_navigation_cubit.freezed.dart
  mobile/lib/cubits/main_navigation/main_navigation_state.dart
  mobile/lib/cubits/playback/playback_cubit.dart
  mobile/lib/cubits/playback/playback_cubit.freezed.dart
  mobile/lib/cubits/playback/playback_state.dart
  mobile/lib/cubits/playback/playback_status/playback_status_cubit.dart
  mobile/lib/cubits/playback/playback_status/playback_status_cubit.freezed.dart
  mobile/lib/cubits/playback/playback_status/playback_status_state.dart
  mobile/lib/helpers/math/clamp.dart
  mobile/lib/models/playback/playback_actions.dart
  mobile/lib/models/playback/playback_actions.freezed.dart
  mobile/lib/models/playback/playback_data.dart
  mobile/lib/models/playback/playback_data.freezed.dart
  mobile/lib/models/playback/playback_duration.dart
  mobile/lib/models/playback/playback_duration.freezed.dart
  mobile/lib/models/playback/playback_event_data.dart
  mobile/lib/models/playback/playback_repeat_mode.dart
  mobile/lib/models/playback/playback_time.dart
  mobile/lib/routes.dart
  mobile/lib/routes/content_routes.dart
  mobile/lib/routes/main_routes.dart
  mobile/lib/screens/main/home/home_screen.dart
  mobile/lib/screens/main/main_screen.dart
  mobile/lib/screens/main/player/player.dart
  mobile/lib/screens/main/player/player_body.dart
  mobile/lib/screens/main/player/player_header.dart
  mobile/lib/screens/main/player/player_screen.dart
  mobile/lib/screens/playlists/playlist_header_info.dart
  mobile/lib/screens/playlists/playlist_screen.dart
  mobile/lib/services/playback/playback_handler.dart
  mobile/lib/services/playback/playback_service.dart
  mobile/lib/widgets/player/player.dart
  mobile/lib/widgets/songs/song_row.dart
Labels: enhancement

#164 Move main and perflow-studio to a common module. Fix bugs
  frontend/src/app/app-routing.module.ts
  frontend/src/app/modules/main-content-container/main-content-container.module.ts
  frontend/src/app/modules/main-content-container/main-content-routing.module.ts
  frontend/src/app/modules/main-content-container/main-content/main-content.component.html
  frontend/src/app/modules/main-content-container/main-content/main-content.component.sass
  frontend/src/app/modules/main-content-container/main-content/main-content.component.ts
  frontend/src/app/modules/main-content-container/music-components/playing/playing.component.html
  frontend/src/app/modules/main-content-container/music-components/playing/playing.component.sass
  frontend/src/app/modules/main-content-container/music-components/playing/playing.component.spec.ts
  frontend/src/app/modules/main-content-container/music-components/playing/playing.component.ts
  frontend/src/app/modules/main-content-container/music-components/queue/queue.component.html
  frontend/src/app/modules/main-content-container/music-components/queue/queue.component.sass
  frontend/src/app/modules/main-content-container/music-components/queue/queue.component.spec.ts
  frontend/src/app/modules/main-content-container/music-components/queue/queue.component.ts
  frontend/src/app/modules/main-content-container/music-components/song-toolbar/song-toolbar.component.html
  frontend/src/app/modules/main-content-container/music-components/song-toolbar/song-toolbar.component.sass
  frontend/src/app/modules/main-content-container/music-components/song-toolbar/song-toolbar.component.spec.ts
  frontend/src/app/modules/main-content-container/music-components/song-toolbar/song-toolbar.component.ts
  frontend/src/app/modules/main-content-container/profile-menu/profile-menu.component.html
  frontend/src/app/modules/main-content-container/profile-menu/profile-menu.component.sass
  frontend/src/app/modules/main-content-container/profile-menu/profile-menu.component.spec.ts
  frontend/src/app/modules/main-content-container/profile-menu/profile-menu.component.ts
  frontend/src/app/modules/main/album-details/album-details.component.ts
  frontend/src/app/modules/main/main-menu-profile/main-menu-profile.component.sass
  frontend/src/app/modules/main/main-menu-profile/main-menu-profile.component.spec.ts
  frontend/src/app/modules/main/main-menu/main-menu.component.html
  frontend/src/app/modules/main/main-menu/main-menu.component.ts
  frontend/src/app/modules/main/main-routing.module.ts
  frontend/src/app/modules/main/main.module.ts
  frontend/src/app/modules/main/playlist/album-list/album-list.component.ts
  frontend/src/app/modules/main/playlist/all/all.component.ts
  frontend/src/app/modules/main/playlist/artist-list/artist-list.component.ts
  frontend/src/app/modules/main/settings/settings.component.html
  frontend/src/app/modules/main/settings/settings.component.sass
  frontend/src/app/modules/main/user-profile/user-profile.component.ts
  frontend/src/app/modules/perflow-studio/main-page/main-page.component.html
  frontend/src/app/modules/shared/shared.module.ts
  frontend/src/app/services/auth/auth.service.ts
  frontend/src/styles.sass
Labels: bug, enhancement

#176 Added ability to save song volume to the local storage
  frontend/src/app/modules/main-content-container/music-components/song-toolbar/song-toolbar.component.ts
Labels: enhancement

#175 Mobile update home screen
  mobile/lib/cubits/common/api_call_cubit.dart
  mobile/lib/cubits/home/home_playlists_cubit.dart
  mobile/lib/cubits/playlists/playlist_songs_cubit.dart
  mobile/lib/screens/main/home/home_screen.dart
  mobile/lib/screens/playlists/playlist_header_info.dart
  mobile/lib/screens/playlists/playlist_screen.dart
  mobile/lib/widgets/cards/medium_content_card.dart
  mobile/lib/widgets/cards/small_content_card.dart
  mobile/lib/widgets/songs/song_row.dart
Labels: enhancement

#178 Removed ability to edit playlist for not author
  frontend/src/app/modules/main/view-playlist/view-playlist.component.html
Labels: bug

#180 Added filtering top artists by role
  backend/Perflow/Services/Implementations/ArtistService.cs
Labels: bug

#179 Bugfix/edit api songs liked request
  backend/Perflow/Common/DTO/Albums/AlbumNameDTO.cs
  backend/Perflow/Common/DTO/Groups/GroupNameDTO.cs
  backend/Perflow/Common/DTO/Songs/SongLikedDTO.cs
  backend/Perflow/Common/DTO/Users/ArtistNameDTO.cs
  backend/Perflow/Common/MappingProfiles/AlbumProfile.cs
  backend/Perflow/Common/MappingProfiles/GroupProfile.cs
  backend/Perflow/Common/MappingProfiles/SongProfile.cs
  backend/Perflow/Common/MappingProfiles/UserProfile.cs
  backend/Perflow/Controllers/SongsController.cs
  backend/Perflow/Services/Implementations/SongsService.cs
  backend/Perflow/Services/Interfaces/ISongsService.cs
  frontend/src/app/models/song/song-liked.ts
Labels: bug

#177 Load playlists by user id in perflow studio
  frontend/src/app/modules/main/main.module.ts
  frontend/src/app/modules/perflow-studio/playlists-page/playlists-page.component.html
  frontend/src/app/modules/perflow-studio/playlists-page/playlists-page.component.sass
  frontend/src/app/modules/perflow-studio/playlists-page/playlists-page.component.ts
Labels: enhancement

#182 Hide scroll buttons when there is no scroll
  frontend/src/app/modules/main/album-details/album-details.component.html
  frontend/src/app/modules/main/album-details/album-details.component.sass
  frontend/src/app/modules/main/album-details/album-details.component.ts
  frontend/src/app/modules/main/main-home/main-home.component.html
  frontend/src/app/modules/main/main-home/main-home.component.sass
  frontend/src/app/modules/main/main-home/main-home.component.ts
  frontend/src/app/modules/main/user-profile/user-profile.component.html
  frontend/src/app/modules/main/user-profile/user-profile.component.sass
  frontend/src/app/modules/shared/directives/hide-scroll-button/hide-scroll-buttons.directive.ts
  frontend/src/app/modules/shared/shared.module.ts
Labels: enhancement

#209 Add song processing
  backend/ApiGateway/ApiGateway/Configuration/Production/songs.json
  backend/Perflow/Common/DTO/Songs/SongReadDTO.cs
  backend/Perflow/Common/Helpers/SongExtensions.cs
  backend/Perflow/Common/MappingProfiles/SongProfile.cs
  backend/Perflow/Controllers/SongsController.cs
  backend/Perflow/Domain/Enums/SongQualityLevel.cs
  backend/Perflow/Domain/Song.cs
  backend/Perflow/Migrations/20210828094416_AddSongQualityLevels.Designer.cs
  backend/Perflow/Migrations/20210828094416_AddSongQualityLevels.cs
  backend/Perflow/Migrations/PerflowContextModelSnapshot.cs
  backend/Perflow/Services/Extensions/AddProcessorRabbitMQ.cs
  backend/Perflow/Services/Extensions/ServiceExtensions.cs
  backend/Perflow/Services/Implementations/SongFilesService.cs
  backend/Perflow/Services/Implementations/SongsService.cs
  backend/Perflow/Services/Implementations/SongsUploadService.cs
  backend/Perflow/Services/Interfaces/ISongFilesService.cs
  backend/Perflow/Services/Interfaces/ISongsService.cs
  backend/Perflow/Services/Interfaces/ISongsUploadService.cs
  backend/Perflow/appsettings.json
  backend/Processor/Processor.ConsoleApp/Implementations/DefaultContainer.cs
  backend/Processor/Processor.ConsoleApp/Implementations/ImageProcessingHandler.cs
  backend/Processor/Processor.ConsoleApp/Implementations/SongProcessingHandler.cs
  backend/Processor/Processor.ConsoleApp/Implementations/SongsProcessingService.cs
  backend/Shared/Shared/AzureBlobStorage/Interfaces/IBlobService.cs
  backend/Shared/Shared/AzureBlobStorage/Services/BlobService.cs
  backend/Shared/Shared/Processor/Models/SongProcessingOptions.cs
  frontend/src/app/models/song/song.ts
  frontend/src/app/modules/perflow-studio/create-edit-album/create-edit-album/create-edit-album.component.ts
  frontend/src/app/services/queue.service.ts
  frontend/src/app/services/songs/songs.service.ts
Labels: enhancement

#210 Playlist settings box. Add logic to Edit details, Delete, Create playlist, Share
  frontend/src/app/modules/main/main-menu/main-menu.component.html
  frontend/src/app/modules/main/main-menu/main-menu.component.ts
  frontend/src/app/modules/main/view-playlist/view-playlist.component.html
  frontend/src/app/modules/main/view-playlist/view-playlist.component.ts
  frontend/src/app/modules/perflow-studio/create-edit-album/create-edit-album/create-edit-album.component.ts
  frontend/src/app/modules/shared/create-edit-playlist/create-edit-playlist/create-edit-playlist.component.ts
Labels: bug, enhancement

#213 Load songs based on audio quality settings
  backend/Perflow/Common/Helpers/SongExtensions.cs
  backend/Perflow/Common/Helpers/UsersServiceExtensions.cs
  backend/Perflow/Controllers/SongsController.cs
  backend/Perflow/Domain/Enums/SongQualityLevel.cs
  backend/Perflow/Services/Implementations/SongFilesService.cs
  backend/Perflow/Services/Interfaces/ISongFilesService.cs
  backend/Shared/Shared/Auth/Extensions/ClaimsExtensions.cs
  frontend/src/app/modules/main-content-container/music-components/song-toolbar/song-toolbar.component.html
  frontend/src/app/services/queue.service.ts
Labels: enhancement

#214 Implemented logic save-play buttons on the main page
  backend/Perflow/Common/DTO/Albums/AlbumForNewestFiveDTO.cs
  backend/Perflow/Controllers/AlbumsController.cs
  backend/Perflow/Services/Implementations/AlbumsService.cs
  frontend/src/app/models/album/newest-five.ts
  frontend/src/app/modules/main/album-details/album-details.component.ts
  frontend/src/app/modules/main/main-home/main-home.component.html
  frontend/src/app/modules/main/main-home/main-home.component.sass
  frontend/src/app/modules/main/main-home/main-home.component.ts
Labels: enhancement

#215 Buttons Add to playlist and Remove from playlist should work
  backend/ApiGateway/ApiGateway/Configuration/Development/playlists.json
  backend/ApiGateway/ApiGateway/Configuration/Production/playlists.json
  backend/Perflow/Controllers/PlaylistsController.cs
  backend/Perflow/Services/Implementations/PlaylistService.cs
  frontend/src/app/modules/main/main-menu/main-menu.component.ts
  frontend/src/app/modules/main/view-playlist/view-playlist.component.html
  frontend/src/app/modules/main/view-playlist/view-playlist.component.ts
  frontend/src/app/modules/shared/playlist/create-playlist/create-playlist.service.ts
  frontend/src/app/modules/shared/song-row/song-row.component.html
  frontend/src/app/modules/shared/song-row/song-row.component.sass
  frontend/src/app/modules/shared/song-row/song-row.component.ts
  frontend/src/app/services/playlists/playlist.service.ts
Labels: enhancement

#216 Fix artist-applicants bug
  frontend/src/app/modules/login-other/other-page/other-page/other-page.component.ts
Labels: bug, important

#212 Feature/add notifications
  backend/ApiGateway/ApiGateway/Configuration/Development/notifications.json
  backend/ApiGateway/ApiGateway/Configuration/Production/notifications.json
  backend/Perflow/Common/DTO/Notifications/NotificationReadDTO.cs
  backend/Perflow/Common/DTO/Notifications/NotificationWriteDTO.cs
  backend/Perflow/Common/MappingProfiles/NotificationProfile.cs
  backend/Perflow/Controllers/NotificationsController.cs
  backend/Perflow/Domain/Enums/NotificationType.cs
  backend/Perflow/Domain/Notification.cs
  backend/Perflow/Hubs/Implementations/NotificationsHub.cs
  backend/Perflow/Hubs/Interfaces/INotificationsHub.cs
  backend/Perflow/Migrations/20210827150513_AddTypeToNotification.Designer.cs
  backend/Perflow/Migrations/20210827150513_AddTypeToNotification.cs
  backend/Perflow/Migrations/PerflowContextModelSnapshot.cs
  backend/Perflow/Services/Extensions/ServiceExtensions.cs
  backend/Perflow/Services/Implementations/AlbumsService.cs
  backend/Perflow/Services/Implementations/NotificationService.cs
  backend/Perflow/Services/Interfaces/INotificationService.cs
  backend/Shared/Shared/Auth/Extensions/AddAuthExtension.cs
  frontend/src/app/models/enums/notification-type.ts
  frontend/src/app/models/notification/notification.ts
  frontend/src/app/models/user/artist-name.ts
  frontend/src/app/modules/main-content-container/main-content-container.module.ts
  frontend/src/app/modules/main-content-container/main-content/main-content.component.html
  frontend/src/app/modules/main-content-container/main-content/main-content.component.sass
  frontend/src/app/modules/main-content-container/notifications/notifications.component.html
  frontend/src/app/modules/main-content-container/notifications/notifications.component.sass
  frontend/src/app/modules/main-content-container/notifications/notifications.component.spec.ts
  frontend/src/app/modules/main-content-container/notifications/notifications.component.ts
  frontend/src/app/modules/main-content-container/profile-menu/profile-menu.component.sass
  frontend/src/app/modules/main/artist-details/artist-details.component.ts
  frontend/src/app/services/hubs/hub-factory.service.ts
  frontend/src/app/services/hubs/notifications-hub.service.ts
  frontend/src/app/services/notification.service.ts
  frontend/src/app/typings.d.ts
Labels: enhancement

#217 add ability to delete a notification
  backend/ApiGateway/ApiGateway/Configuration/Development/notifications.json
  backend/ApiGateway/ApiGateway/Configuration/Production/notifications.json
  backend/Perflow/Common/DTO/Notifications/NotificationChangeStateDTO.cs
  backend/Perflow/Common/DTO/Notifications/NotificationReadDTO.cs
  backend/Perflow/Common/DTO/Notifications/NotificationWriteDTO.cs
  backend/Perflow/Controllers/NotificationsController.cs
  backend/Perflow/Hubs/CustomUserIdProvider.cs
  backend/Perflow/Hubs/Extensions/AddUserIdProviderExtension.cs
  backend/Perflow/Hubs/Implementations/NotificationsHub.cs
  backend/Perflow/Hubs/Interfaces/INotificationsHub.cs
  backend/Perflow/Services/Implementations/AlbumsService.cs
  backend/Perflow/Services/Implementations/NotificationService.cs
  backend/Perflow/Services/Interfaces/INotificationService.cs
  backend/Perflow/Startup.cs
  frontend/src/app/models/notification/notification-change-state.ts
  frontend/src/app/models/notification/notification.ts
  frontend/src/app/modules/main-content-container/notifications/notifications.component.html
  frontend/src/app/modules/main-content-container/notifications/notifications.component.sass
  frontend/src/app/modules/main-content-container/notifications/notifications.component.ts
  frontend/src/app/modules/main/artist-details/artist-details.component.ts
  frontend/src/app/services/hubs/hub-factory.service.ts
  frontend/src/app/services/hubs/notifications-hub.service.ts
  frontend/src/app/services/notification.service.ts
Labels: enhancement

#220 Add imageUrl to album in liked songs
  backend/Perflow/Common/DTO/Albums/AlbumNameDTO.cs
Labels: enhancement

#221 List of liked songs
  mobile/lib/cubits/library_navigation/library_navigation_cubit.dart
  mobile/lib/cubits/library_navigation/library_navigation_cubit.freezed.dart
  mobile/lib/cubits/library_navigation/library_navigation_state.dart
  mobile/lib/cubits/songs/liked_songs_cubit.dart
  mobile/lib/routes.dart
  mobile/lib/routes/main_routes.dart
  mobile/lib/screens/main/library/library_screen.dart
  mobile/lib/screens/main/library/library_songs_screen.dart
  mobile/lib/services/songs/songs_api.chopper.dart
  mobile/lib/services/songs/songs_api.dart
Labels: enhancement

#222 Fix processor permissions
  backend/Processor/Processor.ConsoleApp/Implementations/MessageHandlerBase.cs
  backend/Processor/Processor.ConsoleApp/Implementations/SongProcessingHandler.cs
Labels: bug, important

#223 Processor Update RunBashCommand
  backend/Processor/Processor.ConsoleApp/Implementations/SongProcessingHandler.cs
Labels: bug, important
