Repository BinaryStudioAcademy/bsa-2021-perflow, pull requests merged in 2021-09, with the labels that each got.

#231 Fix ocelot production scheme
  backend/ApiGateway/ApiGateway/Configuration/Production/studio.songs.json
Labels: bug

#233 fix ocelot
  backend/ApiGateway/ApiGateway/Configuration/Production/notifications.json
Labels: bug

#234 test signalr
  backend/Perflow/Hubs/Implementations/NotificationsHub.cs
  frontend/src/app/services/hubs/hub-factory.service.ts
  frontend/src/app/services/hubs/notifications-hub.service.ts
Labels: bug

#235 change skipNegotiation
  frontend/src/app/services/hubs/hub-factory.service.ts
Labels: bug

#236 update hubFactory
  frontend/src/app/services/hubs/hub-factory.service.ts
Labels: bug

#237 change cors
  backend/Perflow/Startup.cs
  frontend/src/app/services/hubs/hub-factory.service.ts
Labels: bug

#238 Bugfix/update ocelot
  backend/ApiGateway/ApiGateway/Configuration/Development/notifications.json
  backend/ApiGateway/ApiGateway/Configuration/Production/notifications.json
  backend/ApiGateway/ApiGateway/Startup.cs
Labels: bug

#241 delete cors
  backend/ApiGateway/ApiGateway/Startup.cs
Labels: bug

#242 wss -> ws
  backend/ApiGateway/ApiGateway/Configuration/Development/notifications.json
  backend/ApiGateway/ApiGateway/Configuration/Production/notifications.json
Labels: bug

#245 Perflow studio - add applicants
  backend/ApiGateway/ApiGateway/Configuration/Development/applicants.json
  backend/ApiGateway/ApiGateway/Configuration/Production/applicants.json
  backend/Perflow/Common/DTO/Applicants/EditApplicantStatusDTO.cs
  backend/Perflow/Common/DTO/Applicants/EditUserRoleDTO.cs
  backend/Perflow/Common/DTO/Applicants/UserWithStatusDTO.cs
  backend/Perflow/Controllers/ApplicantsController.cs
  backend/Perflow/Services/Extensions/ServiceExtensions.cs
  backend/Perflow/Services/Implementations/ApplicantsService.cs
  frontend/src/app/models/applicants/application-status.ts
  frontend/src/app/models/applicants/edit-user-role.ts
  frontend/src/app/models/applicants/user-status-response.ts
  frontend/src/app/models/applicants/user-with-status.ts
  frontend/src/app/modules/perflow-studio/applications-page/applications-page.component.html
  frontend/src/app/modules/perflow-studio/applications-page/applications-page.component.sass
  frontend/src/app/modules/perflow-studio/applications-page/applications-page.component.ts
  frontend/src/app/modules/perflow-studio/applications-page/components/aplicant-row/aplicant-row.component.html
  frontend/src/app/modules/perflow-studio/applications-page/components/aplicant-row/aplicant-row.component.sass
  frontend/src/app/modules/perflow-studio/applications-page/components/aplicant-row/aplicant-row.component.spec.ts
  frontend/src/app/modules/perflow-studio/applications-page/components/aplicant-row/aplicant-row.component.ts
  frontend/src/app/modules/perflow-studio/applications-page/components/role-row/role-row.component.html
  frontend/src/app/modules/perflow-studio/applications-page/components/role-row/role-row.component.sass
  frontend/src/app/modules/perflow-studio/applications-page/components/role-row/role-row.component.spec.ts
  frontend/src/app/modules/perflow-studio/applications-page/components/role-row/role-row.component.ts
  frontend/src/app/modules/perflow-studio/perflow-studio.module.ts
  frontend/src/app/modules/shared/pipes/user-role.pipe.ts
  frontend/src/app/modules/shared/shared.module.ts
  frontend/src/app/services/applicants.service.ts
Labels: enhancement

#246 Add notification if user becomes an artist or moderator
  backend/Perflow/Domain/Enums/NotificationType.cs
  backend/Perflow/Services/Implementations/ApplicantsService.cs
  backend/Perflow/Services/Implementations/NotificationService.cs
  backend/Perflow/Services/Interfaces/INotificationService.cs
Labels: enhancement

#244 Add collaborative playlists
  backend/ApiGateway/ApiGateway/Configuration/Development/playlistEditors.json
  backend/ApiGateway/ApiGateway/Configuration/Production/playlistEditors.json
  backend/Perflow/Common/DTO/PlaylistEditors/PlaylistEditorDTO.cs
  backend/Perflow/Common/DTO/Playlists/PlaylistNameDTO.cs
  backend/Perflow/Common/DTO/Playlists/PlaylistViewDTO.cs
  backend/Perflow/Common/MappingProfiles/PlaylistEditorProfile.cs
  backend/Perflow/Common/MappingProfiles/PlaylistProfile.cs
  backend/Perflow/Controllers/PlaylistEditorsController.cs
  backend/Perflow/DataAccess/Context/EntityTypeConfigurations/PlaylistEditorConfiguration.cs
  backend/Perflow/DataAccess/Context/ModelBuilderExtensions.cs
  backend/Perflow/DataAccess/Context/PerflowContext.cs
  backend/Perflow/Domain/PlaylistEditor.cs
  backend/Perflow/Migrations/20210831061640_AddPlaylistEditors.Designer.cs
  backend/Perflow/Migrations/20210831061640_AddPlaylistEditors.cs
  backend/Perflow/Migrations/PerflowContextModelSnapshot.cs
  backend/Perflow/Services/Extensions/ServiceExtensions.cs
  backend/Perflow/Services/Implementations/PlaylistEditorsService.cs
  frontend/src/app/models/playlist/editedPlaylist.ts
  frontend/src/app/models/playlist/playlist-editor.ts
  frontend/src/app/models/playlist/playlist-name.ts
  frontend/src/app/models/playlist/playlist-view.ts
  frontend/src/app/modules/main/artist-details/artist-details.component.html
  frontend/src/app/modules/main/artist-details/artist-details.component.ts
  frontend/src/app/modules/main/main-menu/main-menu.component.html
  frontend/src/app/modules/main/main-menu/main-menu.component.sass
  frontend/src/app/modules/main/main-menu/main-menu.component.ts
  frontend/src/app/modules/main/user-profile/user-profile.component.html
  frontend/src/app/modules/main/user-profile/user-profile.component.sass
  frontend/src/app/modules/main/user-profile/user-profile.component.ts
  frontend/src/app/modules/main/view-playlist/view-playlist.component.html
  frontend/src/app/modules/main/view-playlist/view-playlist.component.ts
  frontend/src/app/modules/perflow-studio/playlists-page/playlists-page.component.html
  frontend/src/app/modules/perflow-studio/playlists-page/playlists-page.component.ts
  frontend/src/app/modules/shared/create-edit-playlist/colaborative-modal/colaborative-modal.component.html
  frontend/src/app/modules/shared/create-edit-playlist/colaborative-modal/colaborative-modal.component.sass
  frontend/src/app/modules/shared/create-edit-playlist/colaborative-modal/colaborative-modal.component.spec.ts
  frontend/src/app/modules/shared/create-edit-playlist/colaborative-modal/colaborative-modal.component.ts
  frontend/src/app/modules/shared/create-edit-playlist/create-edit-playlist/create-edit-playlist.component.html
  frontend/src/app/modules/shared/create-edit-playlist/create-edit-playlist/create-edit-playlist.component.ts
  frontend/src/app/modules/shared/create-edit-playlist/edit-playlist-modal/edit-playlist-modal.component.html
  frontend/src/app/modules/shared/create-edit-playlist/edit-playlist-modal/edit-playlist-modal.component.sass
  frontend/src/app/modules/shared/create-edit-playlist/edit-playlist-modal/edit-playlist-modal.component.ts
  frontend/src/app/modules/shared/shared.module.ts
  frontend/src/app/services/playlists/playlist-editors.service.ts
Labels: enhancement

#249 Fix artists/playlists icons showing
  backend/Perflow/Services/Implementations/ConstructorService.cs
Labels: bug

#251 Fix access to published container for all users
  backend/Perflow/Controllers/ConstructorController.cs
Labels: bug

#254 fix playlist null description; add releaseYear validator; artist shou…
  frontend/src/app/helpers/object-to-formData-converter.ts
  frontend/src/app/modules/main/artist-details/artist-details.component.html
  frontend/src/app/modules/main/artist-details/artist-details.component.ts
  frontend/src/app/modules/perflow-studio/create-edit-album/edit-album-modal/edit-album-modal.component.html
  frontend/src/app/modules/perflow-studio/create-edit-album/edit-album-modal/edit-album-modal.component.sass
  frontend/src/app/modules/perflow-studio/create-edit-album/edit-album-modal/edit-album-modal.component.ts
  frontend/src/app/services/playlists/playlist.service.ts
Labels: bug

#253 Feature/adding removing to queue
  frontend/src/app/modules/main-content-container/music-components/queue/queue.component.html
  frontend/src/app/modules/shared/song-row/song-row.component.html
  frontend/src/app/modules/shared/song-row/song-row.component.ts
  frontend/src/app/modules/shared/songs-list/songs-list.component.html
  frontend/src/app/modules/shared/songs-list/songs-list.component.ts
Labels: enhancement

#255 Send notifications when added as collaborative
  backend/Perflow/Controllers/SearchController.cs
  backend/Perflow/Domain/Enums/NotificationType.cs
  backend/Perflow/Services/Implementations/AlbumsService.cs
  backend/Perflow/Services/Implementations/NotificationService.cs
  backend/Perflow/Services/Implementations/PlaylistEditorsService.cs
  backend/Perflow/Services/Implementations/SearchService.cs
  backend/Perflow/Services/Interfaces/INotificationService.cs
  frontend/src/app/models/enums/notification-type.ts
  frontend/src/app/modules/main-content-container/notifications/notifications.component.html
  frontend/src/app/modules/main-content-container/notifications/notifications.component.ts
  frontend/src/app/modules/shared/create-edit-playlist/colaborative-modal/colaborative-modal.component.ts
  frontend/src/app/modules/shared/create-edit-playlist/create-edit-playlist/create-edit-playlist.component.html
  frontend/src/app/modules/shared/create-edit-playlist/create-edit-playlist/create-edit-playlist.component.ts
  frontend/src/app/modules/shared/create-edit-playlist/edit-playlist-modal/edit-playlist-modal.component.ts
  frontend/src/app/services/search.service.ts
Labels: enhancement

#256 Group participants should receive notifications
  backend/Perflow/Domain/Enums/NotificationType.cs
  backend/Perflow/Services/Implementations/ApplicantsService.cs
  frontend/src/app/models/enums/notification-type.ts
  frontend/src/app/modules/main-content-container/notifications/notifications.component.html
Labels: enhancement

#258 Added ability to delete user from the collaborative playlist
  backend/Perflow/Controllers/PlaylistEditorsController.cs
  backend/Perflow/Services/Implementations/PlaylistEditorsService.cs
  frontend/src/app/modules/main/main-menu/main-menu.component.html
  frontend/src/app/modules/main/main-menu/main-menu.component.ts
  frontend/src/app/modules/shared/song-row/song-row.component.ts
  frontend/src/app/services/playlists/playlist-editors.service.ts
Labels: enhancement

#259 Added migration AddGroupArtistTable, remade code according to changes
  backend/Perflow/DataAccess/Context/EntityTypeConfigurations/GroupConfiguration.cs
  backend/Perflow/DataAccess/Context/EntityTypeConfigurations/UserConfiguration.cs
  backend/Perflow/DataAccess/Context/ModelBuilderExtensions.cs
  backend/Perflow/DataAccess/Context/PerflowContext.cs
  backend/Perflow/Domain/Group.cs
  backend/Perflow/Domain/GroupArtist.cs
  backend/Perflow/Domain/User.cs
  backend/Perflow/Migrations/20210903180459_AddGroupArtistTable.Designer.cs
  backend/Perflow/Migrations/20210903180459_AddGroupArtistTable.cs
  backend/Perflow/Migrations/PerflowContextModelSnapshot.cs
  backend/Perflow/Services/Implementations/AlbumReactionService.cs
  backend/Perflow/Services/Implementations/AlbumsService.cs
  backend/Perflow/Services/Implementations/ApplicantsService.cs
  backend/Perflow/Services/Implementations/GroupService.cs
  backend/Perflow/Services/Implementations/PlaylistService.cs
Labels: enhancement

#260 Add content sync
  backend/ApiGateway/ApiGateway/Configuration/Production/contentSynchronization.json
  backend/Perflow/Hubs/Extensions/AddUserIdProviderExtension.cs
  backend/Perflow/Hubs/Implementations/CustomUserIdProvider.cs
  backend/Perflow/Hubs/Implementations/NotificationsHub.cs
  backend/Perflow/Hubs/Implementations/SynchronizationHub.cs
  backend/Perflow/Hubs/Interfaces/ISynchronizationHub.cs
  backend/Perflow/Services/Extensions/AddPerflowAuthExtension.cs
  backend/Perflow/Services/Implementations/ContentSynchronizationService.cs
  backend/Perflow/Services/Implementations/NotificationService.cs
  backend/Perflow/Startup.cs
  backend/Shared/Shared/Auth/Extensions/AddAuthExtension.cs
  frontend/src/app/modules/main-content-container/music-components/song-toolbar/song-toolbar.component.ts
  frontend/src/app/modules/main/cards/playlist-card/playlist-card.component.spec.ts
  frontend/src/app/modules/shared/directives/calendar/semantic-calendar.directive.spec.ts
  frontend/src/app/modules/shared/directives/message/semantic-message.directive.spec.ts
  frontend/src/app/services/content-synchronization.service.ts
  frontend/src/app/services/hubs/base-hub.service.ts
  frontend/src/app/services/hubs/content-sync-hub.service.ts
  frontend/src/app/services/hubs/hub-factory.service.ts
  frontend/src/app/services/hubs/notifications-hub.service.ts
  frontend/src/app/services/song-toolbar.service.ts
  mobile/lib/configure_services.config.dart
  mobile/lib/cubits/artists/artist_songs_cubit.dart
  mobile/lib/cubits/playlists/playlist_songs_cubit.dart
  mobile/lib/models/playback/playback_duration.dart
  mobile/lib/models/playback/playback_duration.freezed.dart
  mobile/lib/models/playback_sync/playback_sync_data.dart
  mobile/lib/models/playback_sync/playback_sync_data.freezed.dart
  mobile/lib/models/playback_sync/playback_sync_data.g.dart
  mobile/lib/services/playback/playback_handler.dart
  mobile/lib/services/playback/playback_service.dart
  mobile/lib/services/playback/playback_sync_hub.dart
  mobile/lib/services/signalr/base_hub_service.dart
  mobile/lib/services/signalr/hub_factory_service.dart
  mobile/lib/widgets/songs/song_row.dart
  mobile/pubspec.lock
  mobile/pubspec.yaml
Labels: enhancement

#263 Feature/add user mix
  backend/ApiGateway/ApiGateway/Configuration/Development/playlists.json
  backend/ApiGateway/ApiGateway/Configuration/Production/playlists.json
  backend/Perflow/Common/DTO/Playlists/PlaylistDTO.cs
  backend/Perflow/Controllers/PlaylistsController.cs
  backend/Perflow/DataAccess/Context/EntityTypeConfigurations/AlbumConfiguration.cs
  backend/Perflow/Domain/Enums/PlaylistType.cs
  backend/Perflow/Domain/Group.cs
  backend/Perflow/Domain/Playlist.cs
  backend/Perflow/Domain/Song.cs
  backend/Perflow/Migrations/20210904101516_AddTypeToPlaylist.Designer.cs
  backend/Perflow/Migrations/20210904101516_AddTypeToPlaylist.cs
  backend/Perflow/Migrations/PerflowContextModelSnapshot.cs
  backend/Perflow/Services/Implementations/PlaylistService.cs
  backend/Perflow/Services/Implementations/SearchService.cs
  frontend/src/app/models/enums/playlist-type.ts
  frontend/src/app/models/playlist/playlist.ts
  frontend/src/app/modules/main/cards/your-mix-card/your-mix-card.component.html
  frontend/src/app/modules/main/cards/your-mix-card/your-mix-card.component.sass
  frontend/src/app/modules/main/cards/your-mix-card/your-mix-card.component.ts
  frontend/src/app/modules/main/main-home/main-home.component.html
  frontend/src/app/modules/main/main-home/main-home.component.ts
  frontend/src/app/modules/main/view-playlist/view-playlist.component.html
  frontend/src/app/modules/main/view-playlist/view-playlist.component.sass
  frontend/src/app/modules/main/view-playlist/view-playlist.component.ts
  frontend/src/app/services/playlists/playlist.service.ts
Labels: enhancement

#262 Bugfix/ocelot fix sync
  backend/ApiGateway/ApiGateway/Configuration/Development/contentSynchronization.json
  backend/ApiGateway/ApiGateway/Configuration/Production/contentSynchronization.json
Labels: bug, important

#265 fix playlist view
  frontend/src/app/modules/main/view-playlist/view-playlist.component.sass
Labels: bug

#264 Ability for artist to join to group or create a group
  backend/Perflow/Controllers/SearchController.cs
  backend/Perflow/Domain/Group.cs
  backend/Perflow/Migrations/20210905071551_AddColumnToGroupTable.Designer.cs
  backend/Perflow/Migrations/20210905071551_AddColumnToGroupTable.cs
  backend/Perflow/Migrations/PerflowContextModelSnapshot.cs
  backend/Perflow/Services/Implementations/ApplicantsService.cs
  backend/Perflow/Services/Implementations/GroupService.cs
  backend/Perflow/Services/Implementations/SearchService.cs
  frontend/src/app/modules/login-other/login-other.module.ts
  frontend/src/app/modules/login-other/other-page/artist-applicant-page/artist-applicant-page.component.html
  frontend/src/app/modules/login-other/other-page/artist-applicant-page/artist-applicant-page.component.sass
  frontend/src/app/modules/login-other/other-page/artist-applicant-page/artist-applicant-page.component.ts
  frontend/src/app/modules/login-other/other-page/group-modal/group-modal.component.html
  frontend/src/app/modules/login-other/other-page/group-modal/group-modal.component.sass
  frontend/src/app/modules/login-other/other-page/group-modal/group-modal.component.ts
  frontend/src/app/modules/main/artist-details/artist-details.component.ts
  frontend/src/app/modules/perflow-studio/left-side-menu/left-side-menu.component.html
  frontend/src/app/modules/perflow-studio/perflow-studio-routing.module.ts
  frontend/src/app/modules/perflow-studio/perflow-studio.module.ts
Labels: enhancement

#261 Feature/main page mobile
  mobile/lib/configure_services.config.dart
  mobile/lib/cubits/albums/new_releases_cubit.dart
  mobile/lib/cubits/recently_played/recently_played_cubit.dart
  mobile/lib/cubits/songs/songs_cubit.dart
  mobile/lib/models/recently_played/recently_played_song.dart
  mobile/lib/models/recently_played/recently_played_song.g.dart
  mobile/lib/screens/main/home/home_screen.dart
  mobile/lib/screens/main/library/library_screen.dart
  mobile/lib/screens/main/library/library_songs_screen.dart
  mobile/lib/screens/main/search/search_screen.dart
  mobile/lib/services/albums/albums_api.chopper.dart
  mobile/lib/services/albums/albums_api.dart
  mobile/lib/services/recently_played/recently_played_api.chopper.dart
  mobile/lib/services/recently_played/recently_played_api.dart
  mobile/lib/theme.dart
  mobile/lib/widgets/songs/song_row.dart
Labels: enhancement

#272 Fix content sync
  backend/Perflow/Hubs/Implementations/SynchronizationHub.cs
Labels: bug

#270 Update "publish/unpublish album" logic
  backend/ApiGateway/ApiGateway/Configuration/Development/search.json
  backend/ApiGateway/ApiGateway/Configuration/Production/search.json
  backend/Perflow/Controllers/SearchController.cs
  backend/Perflow/Services/Implementations/AlbumReactionService.cs
  backend/Perflow/Services/Implementations/SearchService.cs
  frontend/src/app/modules/main/search/components/all-albums/all-albums.component.ts
  frontend/src/app/services/search.service.ts
Labels: enhancement

#268 Reduced scrolling size, fixed scrolling arrows
  frontend/src/app/modules/main/main-home/main-home.component.html
  frontend/src/app/modules/main/main-home/main-home.component.ts
Labels: bug

#269 Rename button 'Collaborators' to 'Add Collaborators', add 'Close moda…
  frontend/src/app/modules/shared/create-edit-playlist/colaborative-modal/colaborative-modal.component.html
  frontend/src/app/modules/shared/create-edit-playlist/colaborative-modal/colaborative-modal.component.sass
  frontend/src/app/modules/shared/create-edit-playlist/edit-playlist-modal/edit-playlist-modal.component.html
Labels: bug

#274 Fix bug: Queue doesn't ipen
  frontend/src/app/modules/main-content-container/music-components/song-toolbar/song-toolbar.component.ts
Labels: bug

#271 Feature/search groups show liked groups
  backend/ApiGateway/ApiGateway/Configuration/Development/groupReactions.json
  backend/ApiGateway/ApiGateway/Configuration/Production/groupReactions.json
  backend/Perflow/Common/DTO/Search/SearchHistoryReadDTO.cs
  backend/Perflow/Common/DTO/Search/SearchHistoryWriteDTO.cs
  backend/Perflow/Common/DTO/Search/SearchResultDTO.cs
  backend/Perflow/Common/MappingProfiles/GroupProfile.cs
  backend/Perflow/Controllers/GroupReactionsController.cs
  backend/Perflow/Domain/SearchHistory.cs
  backend/Perflow/Migrations/20210906164556_AddGroupToSearch.Designer.cs
  backend/Perflow/Migrations/20210906164556_AddGroupToSearch.cs
  backend/Perflow/Migrations/PerflowContextModelSnapshot.cs
  backend/Perflow/Services/Implementations/ConstructorService.cs
  backend/Perflow/Services/Implementations/GroupReactionService.cs
  backend/Perflow/Services/Implementations/SearchHistoryService.cs
  backend/Perflow/Services/Implementations/SearchService.cs
  frontend/src/app/models/search/found-data.ts
  frontend/src/app/models/search/read-search-history.ts
  frontend/src/app/models/search/write-search-history.ts
  frontend/src/app/modules/main/cards/artist-card/artist-card.component.html
  frontend/src/app/modules/main/group-view/group-view.component.html
  frontend/src/app/modules/main/group-view/group-view.component.ts
  frontend/src/app/modules/main/main-home/main-home.component.html
  frontend/src/app/modules/main/main-routing.module.ts
  frontend/src/app/modules/main/main.module.ts
  frontend/src/app/modules/main/playlist/artist-list/artist-list.component.html
  frontend/src/app/modules/main/playlist/artist-list/artist-list.component.ts
  frontend/src/app/modules/main/search/components/all-groups/all-groups/all-groups.component.html
  frontend/src/app/modules/main/search/components/all-groups/all-groups/all-groups.component.sass
  frontend/src/app/modules/main/search/components/all-groups/all-groups/all-groups.component.spec.ts
  frontend/src/app/modules/main/search/components/all-groups/all-groups/all-groups.component.ts
  frontend/src/app/modules/main/search/components/search-groups-result/search-groups-result/search-groups-result.component.html
  frontend/src/app/modules/main/search/components/search-groups-result/search-groups-result/search-groups-result.component.sass
  frontend/src/app/modules/main/search/components/search-groups-result/search-groups-result/search-groups-result.component.spec.ts
  frontend/src/app/modules/main/search/components/search-groups-result/search-groups-result/search-groups-result.component.ts
  frontend/src/app/modules/main/search/search.component.html
  frontend/src/app/modules/main/search/search.component.ts
  frontend/src/app/modules/perflow-studio/constructor/container-search-modal/container-search-modal/container-search-modal.component.ts
  frontend/src/app/modules/perflow-studio/constructor/container-search/container-search/container-search.component.html
  frontend/src/app/modules/perflow-studio/constructor/container-search/container-search/container-search.component.ts
  frontend/src/app/modules/perflow-studio/constructor/create-edit-container/create-edit-container/create-edit-container.component.html
  frontend/src/app/modules/perflow-studio/constructor/create-edit-container/create-edit-container/create-edit-container.component.ts
  frontend/src/app/services/reaction.service.ts
Labels: enhancement

#277 Update project's ports to locally launch it through ApiGateway
  backend/ApiGateway/ApiGateway/Startup.cs
  backend/Perflow.Studio/Properties/launchSettings.json
  backend/Perflow.Studio/appsettings.json
  frontend/src/environments/environment.ts
Labels: bug

#275 Fix collaborative playlist renaming
  frontend/src/app/modules/main/main-menu/main-menu.component.ts
  frontend/src/app/modules/shared/create-edit-playlist/create-edit-playlist/create-edit-playlist.component.ts
  frontend/src/app/modules/shared/playlist/create-playlist/create-playlist.service.ts
Labels: bug

#279 Feature/renaming-product-owner-suggestions
  frontend/src/app/modules/shared/pipes/access-type.pipe.ts
  frontend/src/app/modules/shared/song-row/song-row.component.html
Labels: enhancement

#276 Feature/user and album avatar ability to crop image
  frontend/src/app/modules/perflow-studio/create-edit-album/edit-album-modal/edit-album-modal.component.html
  frontend/src/app/modules/perflow-studio/create-edit-album/edit-album-modal/edit-album-modal.component.ts
  frontend/src/app/modules/user/profile-edit-form/profile-edit-form.component.html
  frontend/src/app/modules/user/profile-edit-form/profile-edit-form.component.ts
Labels: enhancement

#281 Share play collaborative playlist
  backend/ApiGateway/ApiGateway/Configuration/Development/sharePlay.json
  backend/ApiGateway/ApiGateway/Configuration/Production/sharePlay.json
  backend/Perflow/Common/DTO/ContentSynchronization/SharePlayDTO.cs
  backend/Perflow/Common/DTO/ContentSynchronization/SharePlayDataDTO.cs
  backend/Perflow/Controllers/SharePlayController.cs
  backend/Perflow/DataAccess/Context/PerflowContext.cs
  backend/Perflow/Domain/Enums/NotificationType.cs
  backend/Perflow/Domain/SharePlay.cs
  backend/Perflow/Hubs/Implementations/SharePlayHub.cs
  backend/Perflow/Hubs/Interfaces/ISharePlayHub.cs
  backend/Perflow/Migrations/20210906195555_AddSharePlayTable.Designer.cs
  backend/Perflow/Migrations/20210906195555_AddSharePlayTable.cs
  backend/Perflow/Migrations/PerflowContextModelSnapshot.cs
  backend/Perflow/Services/Extensions/AddPerflowAuthExtension.cs
  backend/Perflow/Services/Extensions/ServiceExtensions.cs
  backend/Perflow/Services/Implementations/SharePlayService.cs
  backend/Perflow/Startup.cs
  frontend/src/app/models/enums/notification-type.ts
  frontend/src/app/models/share-play/share-play-data.ts
  frontend/src/app/models/share-play/share-play.ts
  frontend/src/app/modules/main-content-container/music-components/song-toolbar/song-toolbar.component.ts
  frontend/src/app/modules/main-content-container/notifications/notifications.component.html
  frontend/src/app/modules/main-content-container/notifications/notifications.component.ts
  frontend/src/app/modules/main/view-playlist/view-playlist.component.html
  frontend/src/app/modules/main/view-playlist/view-playlist.component.sass
  frontend/src/app/modules/main/view-playlist/view-playlist.component.ts
  frontend/src/app/services/hubs/share-play-hub.ts
  frontend/src/app/services/share-play.service.ts
Labels: enhancement

#282 update NotificationsHub
  backend/Perflow/Hubs/Implementations/NotificationsHub.cs
Labels: bug

#273 Mobile queue
  mobile/lib/configure_services.config.dart
  mobile/lib/cubits/albums/album_info_cubit.dart
  mobile/lib/cubits/artists/artist_songs_cubit.dart
  mobile/lib/cubits/playback/playback_cubit.dart
  mobile/lib/cubits/playback_queue/playback_queue_cubit.dart
  mobile/lib/cubits/playback_queue/playback_queue_cubit.freezed.dart
  mobile/lib/cubits/playback_queue/playback_queue_state.dart
  mobile/lib/cubits/playlists/playlist_songs_cubit.dart
  mobile/lib/cubits/search/search_songs_cubit.dart
  mobile/lib/models/playback/playback_event_data.dart
  mobile/lib/models/playback/playback_queue_data.dart
  mobile/lib/models/playback/playback_queue_data.freezed.dart
  mobile/lib/models/songs/album_song.dart
  mobile/lib/models/songs/artist_song.dart
  mobile/lib/models/songs/playlist_song.dart
  mobile/lib/models/songs/song.dart
  mobile/lib/models/songs/song.g.dart
  mobile/lib/routes.dart
  mobile/lib/routes/main_routes.dart
  mobile/lib/routes/root_routes.dart
  mobile/lib/screens/albums/album_screen.dart
  mobile/lib/screens/artists/artist_screen.dart
  mobile/lib/screens/details/header.dart
  mobile/lib/screens/details/header_info.dart
  mobile/lib/screens/main/player/player.dart
  mobile/lib/screens/main/player/player_body.dart
  mobile/lib/screens/main/player/player_functions_mixin.dart
  mobile/lib/screens/main/queue/queue_list.dart
  mobile/lib/screens/main/queue/queue_screen.dart
  mobile/lib/screens/main/search/search_screen.dart
  mobile/lib/screens/playlists/playlist_screen.dart
  mobile/lib/services/playback/playback_handler.dart
  mobile/lib/services/playback/playback_handler_register.dart
  mobile/lib/services/playback/playback_manager.dart
  mobile/lib/services/playback/playback_queue.dart
  mobile/lib/services/playback/playback_service.dart
  mobile/lib/services/playback/playback_sync_hub.dart
  mobile/lib/theme.dart
  mobile/lib/widgets/common/content_row.dart
  mobile/lib/widgets/song_dialog/song_dialog.dart
  mobile/lib/widgets/songs/song_row.dart
  mobile/pubspec.lock
  mobile/pubspec.yaml
Labels: enhancement

#283 Bugfix/small fixes
  backend/ApiGateway/ApiGateway/Configuration/Development/groups.json
  backend/ApiGateway/ApiGateway/Configuration/Production/groups.json
  backend/Perflow/Common/DTO/Albums/AlbumForEditGroupViewDTO.cs
  backend/Perflow/Common/MappingProfiles/AlbumProfile.cs
  backend/Perflow/Controllers/AlbumsController.cs
  backend/Perflow/Controllers/GroupsController.cs
  backend/Perflow/Services/Implementations/AlbumsService.cs
  backend/Perflow/Services/Implementations/GroupService.cs
  frontend/src/app/models/album/albumForReadDTO.ts
  frontend/src/app/modules/main/cards/album-card/album-card.component.html
  frontend/src/app/modules/main/cards/album-card/album-card.component.sass
  frontend/src/app/modules/main/cards/album-card/album-card.component.ts
  frontend/src/app/modules/main/group-view/group-view.component.html
  frontend/src/app/modules/main/group-view/group-view.component.sass
  frontend/src/app/modules/main/group-view/group-view.component.ts
  frontend/src/app/modules/perflow-studio/edit-group/edit-group-modal/edit-group-modal.component.ts
  frontend/src/app/modules/perflow-studio/edit-group/edit-group/edit-group/edit-group.component.html
  frontend/src/app/modules/perflow-studio/edit-group/edit-group/edit-group/edit-group.component.sass
  frontend/src/app/modules/perflow-studio/edit-group/edit-group/edit-group/edit-group.component.ts
  frontend/src/app/modules/shared/create-edit-playlist/colaborative-modal/colaborative-modal.component.html
  frontend/src/app/modules/shared/create-edit-playlist/colaborative-modal/colaborative-modal.component.sass
  frontend/src/app/services/group.service.ts
Labels: bug

#285 Bugfix/fix loading api songs
  backend/Perflow/Common/DTO/Albums/AlbumShortDTO.cs
  backend/Perflow/Controllers/ConstructorController.cs
  backend/Perflow/Controllers/SongsController.cs
  backend/Perflow/Services/Implementations/ConstructorService.cs
  backend/Perflow/Services/Implementations/SongsService.cs
  backend/Perflow/Services/Interfaces/ISongsService.cs
  frontend/src/app/models/album/newest-five.ts
  frontend/src/app/modules/main/main-home/main-home.component.ts
Labels: bug

#286 No songs no publishing
  frontend/src/app/modules/perflow-studio/create-edit-album/create-edit-album/create-edit-album.component.html
  frontend/src/app/modules/perflow-studio/create-edit-album/create-edit-album/create-edit-album.component.ts
Labels: enhancement

#287 Changes files
  backend/ApiGateway/ApiGateway/Configuration/Development/contentSynchronization.json
  backend/ApiGateway/ApiGateway/Configuration/Development/notifications.json
  backend/ApiGateway/ApiGateway/Configuration/Development/sharePlay.json
  backend/ApiGateway/ApiGateway/Configuration/Production/contentSynchronization.json
  backend/ApiGateway/ApiGateway/Configuration/Production/notifications.json
  backend/ApiGateway/ApiGateway/Configuration/Production/sharePlay.json
  backend/Perflow/Services/Extensions/AddPerflowAuthExtension.cs
  backend/Perflow/Startup.cs
  frontend/nginx.conf
  frontend/nginx.dev.conf
Labels: bug

#290 Fixed hub routes on the frontend
  frontend/src/app/services/hubs/content-sync-hub.service.ts
  frontend/src/app/services/hubs/notifications-hub.service.ts
  frontend/src/app/services/hubs/share-play-hub.ts
Labels: bug

#289 Unable to edit and delete if it's mix
  frontend/src/app/modules/main/view-playlist/view-playlist.component.html
Labels: enhancement

#291 Remove share buttons
  frontend/src/app/modules/perflow-studio/create-edit-album/create-edit-album/create-edit-album.component.html
  frontend/src/app/modules/perflow-studio/create-edit-album/create-edit-album/create-edit-album.component.ts
  frontend/src/app/modules/shared/create-edit-playlist/create-edit-playlist/create-edit-playlist.component.html
  frontend/src/app/modules/shared/create-edit-playlist/create-edit-playlist/create-edit-playlist.component.ts
Labels: enhancement

#267 Feature/make secret collaborative
  backend/ApiGateway/ApiGateway/Configuration/Development/playlists.json
  backend/ApiGateway/ApiGateway/Configuration/Production/playlists.json
  backend/Perflow/Controllers/PlaylistsController.cs
  backend/Perflow/Services/Implementations/PlaylistService.cs
  frontend/src/app/modules/main/main-menu/main-menu.component.html
  frontend/src/app/modules/main/main-menu/main-menu.component.ts
  frontend/src/app/services/playlists/playlist.service.ts
Labels: enhancement

#292 fix styles of notifications
  frontend/src/app/modules/main-content-container/profile-menu/profile-menu.component.ts
  frontend/src/app/modules/main/album-details/album-details.component.html
  frontend/src/app/modules/main/album-details/album-details.component.ts
  frontend/src/app/modules/main/artist-details/artist-details.component.html
  frontend/src/app/modules/main/artist-details/artist-details.component.ts
  frontend/src/app/modules/main/group-view/group-view.component.html
  frontend/src/app/modules/main/group-view/group-view.component.ts
  frontend/src/app/modules/main/main-home/main-home.component.html
  frontend/src/app/modules/main/main-home/main-home.component.ts
  frontend/src/app/modules/main/main-menu/main-menu.component.html
  frontend/src/app/modules/main/main-menu/main-menu.component.ts
  frontend/src/app/modules/main/user-profile/user-profile.component.html
  frontend/src/app/modules/main/user-profile/user-profile.component.ts
  frontend/src/app/modules/main/view-playlist/view-playlist.component.html
  frontend/src/app/modules/main/view-playlist/view-playlist.component.ts
  frontend/src/app/modules/perflow-studio/create-edit-album/create-edit-album/create-edit-album.component.html
  frontend/src/app/modules/perflow-studio/create-edit-album/create-edit-album/create-edit-album.component.ts
  frontend/src/app/modules/perflow-studio/edit-group/edit-group/edit-group/edit-group.component.html
  frontend/src/app/modules/perflow-studio/edit-group/edit-group/edit-group/edit-group.component.ts
  frontend/src/app/modules/shared/create-edit-playlist/create-edit-playlist/create-edit-playlist.component.html
  frontend/src/app/modules/shared/create-edit-playlist/create-edit-playlist/create-edit-playlist.component.ts
  frontend/src/app/modules/shared/song-row/song-row.component.html
  frontend/src/app/modules/shared/song-row/song-row.component.ts
  frontend/src/app/modules/user/profile-edit-form/profile-edit-form.component.html
  frontend/src/app/modules/user/user-profile-edit/user-profile-edit.component.ts
  frontend/src/app/services/profile.service.ts
Labels: bug

#294 Add to endpoint songs/{id} isLiked field
  backend/Perflow/Common/Helpers/AlbumWithIcon.cs
  backend/Perflow/Common/Helpers/PlaylistWithIcon.cs
  backend/Perflow/Common/Helpers/UserWithIcon.cs
  backend/Perflow/Controllers/SongsController.cs
  backend/Perflow/Services/Implementations/SongsService.cs
  backend/Perflow/Services/Interfaces/ISongsService.cs
Labels: bug

#295 Feature/user should be able to play content on the main page
  backend/ApiGateway/ApiGateway/Configuration/Development/contentSynchronization.json
  backend/ApiGateway/ApiGateway/Configuration/Development/sharePlay.json
  backend/Perflow/Common/DTO/Groups/GroupReadDTO.cs
  backend/Perflow/Common/MappingProfiles/SongProfile.cs
  backend/Perflow/Services/Implementations/SongsService.cs
  frontend/src/app/modules/main/cards/artist-card/artist-card.component.html
  frontend/src/app/modules/main/cards/artist-card/artist-card.component.ts
  frontend/src/app/modules/main/cards/playlist-card/playlist-card.component.ts
  frontend/src/app/modules/main/cards/song-card/song-card.component.html
  frontend/src/app/modules/main/cards/song-card/song-card.component.ts
Labels: enhancement

#298 Feature/add radio logic
  backend/ApiGateway/ApiGateway/Configuration/Development/radio.json
  backend/ApiGateway/ApiGateway/Configuration/Production/radio.json
  backend/Perflow/Common/DTO/Songs/SongLikedDTO.cs
  backend/Perflow/Controllers/RadioController.cs
  backend/Perflow/Services/Extensions/ServiceExtensions.cs
  backend/Perflow/Services/Implementations/RadioService.cs
  backend/Perflow/Services/Implementations/SongsService.cs
  backend/Perflow/Services/Interfaces/IRadioService.cs
  frontend/src/app/modules/main/main-menu/main-menu.component.html
  frontend/src/app/modules/main/main-menu/main-menu.component.ts
  frontend/src/app/modules/main/view-playlist/view-playlist.component.html
  frontend/src/app/modules/main/view-playlist/view-playlist.component.ts
  frontend/src/app/modules/shared/create-edit-playlist/create-edit-playlist/create-edit-playlist.component.html
  frontend/src/app/modules/shared/create-edit-playlist/create-edit-playlist/create-edit-playlist.component.ts
  frontend/src/app/modules/shared/song-row/song-row.component.html
  frontend/src/app/modules/shared/song-row/song-row.component.ts
  frontend/src/app/services/radio.service.ts
  frontend/src/app/services/tags/tag.service.ts
Labels: enhancement

#293 Bugfix/song playing deleting fix
  frontend/src/app/modules/main/view-playlist/view-playlist.component.html
  frontend/src/app/modules/perflow-studio/create-edit-album/create-edit-album/create-edit-album.component.html
  frontend/src/app/modules/perflow-studio/create-edit-album/create-edit-album/create-edit-album.component.ts
  frontend/src/app/modules/shared/song-row/song-row.component.html
  frontend/src/app/modules/shared/song-row/song-row.component.ts
  frontend/src/app/modules/shared/songs-list/songs-list.component.html
  frontend/src/app/modules/shared/songs-list/songs-list.component.ts
Labels: bug

#297 Bugfix/fix ability to share play for collaborative playlist
  backend/ApiGateway/ApiGateway/Configuration/Development/sharePlay.json
  backend/ApiGateway/ApiGateway/Configuration/Production/sharePlay.json
  backend/Perflow/Common/DTO/Hub/CheckStatusDTO.cs
  backend/Perflow/Controllers/SharePlayController.cs
  backend/Perflow/DataAccess/Context/PerflowContext.cs
  backend/Perflow/Domain/SharePlay.cs
  backend/Perflow/Hubs/Implementations/SharePlayHub.cs
  backend/Perflow/Hubs/Interfaces/ISharePlayHub.cs
  backend/Perflow/Migrations/20210908220826_RemoveSharePlayTable.Designer.cs
  backend/Perflow/Migrations/20210908220826_RemoveSharePlayTable.cs
  backend/Perflow/Migrations/PerflowContextModelSnapshot.cs
  backend/Perflow/Services/Implementations/SharePlayService.cs
  frontend/src/app/models/share-play/check-status.ts
  frontend/src/app/modules/main/view-playlist/view-playlist.component.html
  frontend/src/app/modules/main/view-playlist/view-playlist.component.ts
  frontend/src/app/services/hubs/share-play-hub.ts
  frontend/src/app/services/share-play.service.ts
Labels: bug

#296 Add confirmation modal
  frontend/src/app/modules/main-content-container/main-content/main-content.component.html
  frontend/src/app/modules/main-content-container/main-content/main-content.component.ts
  frontend/src/app/modules/main/cards/constructor-container-card/constructor-container-card/constructor-container-card.component.html
  frontend/src/app/modules/main/cards/constructor-container-card/constructor-container-card/constructor-container-card.component.ts
  frontend/src/app/modules/main/main-home/main-home.component.html
  frontend/src/app/modules/main/main-home/main-home.component.ts
  frontend/src/app/modules/main/main-menu/main-menu.component.ts
  frontend/src/app/modules/main/view-playlist/view-playlist.component.html
  frontend/src/app/modules/main/view-playlist/view-playlist.component.ts
  frontend/src/app/modules/perflow-studio/create-edit-album/create-edit-album/create-edit-album.component.html
  frontend/src/app/modules/perflow-studio/create-edit-album/create-edit-album/create-edit-album.component.ts
  frontend/src/app/modules/perflow-studio/edit-group/edit-group/edit-group/edit-group.component.html
  frontend/src/app/modules/perflow-studio/edit-group/edit-group/edit-group/edit-group.component.ts
  frontend/src/app/modules/shared/confirmation-modal/confirmation-modal.component.html
  frontend/src/app/modules/shared/confirmation-modal/confirmation-modal.component.sass
  frontend/src/app/modules/shared/confirmation-modal/confirmation-modal.component.spec.ts
  frontend/src/app/modules/shared/confirmation-modal/confirmation-modal.component.ts
  frontend/src/app/modules/shared/create-edit-playlist/create-edit-playlist/create-edit-playlist.component.html
  frontend/src/app/modules/shared/create-edit-playlist/create-edit-playlist/create-edit-playlist.component.sass
  frontend/src/app/modules/shared/create-edit-playlist/create-edit-playlist/create-edit-playlist.component.ts
  frontend/src/app/modules/shared/shared.module.ts
  frontend/src/app/services/confirmation-page.service.ts
Labels: enhancement

#299 Feature/main page recommendation
  mobile/lib/cubits/playlists/recommended_playlists_cubit.dart
  mobile/lib/screens/main/home/home_screen.dart
  mobile/lib/services/playlists/playlists_api.chopper.dart
  mobile/lib/services/playlists/playlists_api.dart
  mobile/lib/widgets/cards/small_content_card.dart
Labels: enhancement

#302 Added time is displayed after refresh page; Change order. Error 500; Artist should not able to Subscribe own page
  backend/Perflow.Studio/Business/Songs/Handlers/SetSongOrderHandler.cs
  backend/Perflow/Common/DTO/Songs/SongForPlaylistSongSearchDTO.cs
  backend/Perflow/Services/Implementations/SearchService.cs
  frontend/src/app/modules/main/artist-details/artist-details.component.html
Labels: bug

#304 Build and functionality fixes
  mobile/lib/models/playback/playback_queue_data.freezed.dart
  mobile/lib/services/playlists/playlists_api.chopper.dart
  mobile/lib/services/playlists/playlists_api.dart
  mobile/lib/services/search/search_api.chopper.dart
  mobile/lib/services/search/search_api.dart
  mobile/pubspec.lock
  mobile/pubspec.yaml
Labels: bug

#306 bugfix/user-avatar-crop-image
  frontend/src/app/modules/user/profile-edit-form/profile-edit-form.component.html
  frontend/src/app/modules/user/profile-edit-form/profile-edit-form.component.sass
Labels: bug

#301 Feature/notify moderator on new applicants
  backend/Perflow/Services/Implementations/UsersService.cs
  frontend/src/app/modules/shared/songs-list/songs-list.component.html
  frontend/src/app/services/album.service.ts
Labels: enhancement

#305 Feature/transfer endpoints constructor
  backend/ApiGateway/ApiGateway/Configuration/Development/constructor.json
  backend/ApiGateway/ApiGateway/Configuration/Production/constructor.json
  backend/Perflow.Studio/Business/Constructor/Commands/CreatePageContainerCommand.cs
  backend/Perflow.Studio/Business/Constructor/Commands/DeleteContainerCommand.cs
  backend/Perflow.Studio/Business/Constructor/Commands/UpdatePageContainerCommand.cs
  backend/Perflow.Studio/Business/Constructor/DTOs/PageContainerDTO.cs
  backend/Perflow.Studio/Business/Constructor/DTOs/PageContainerViewDTO.cs
  backend/Perflow.Studio/Business/Constructor/DTOs/PageSectionDTO.cs
  backend/Perflow.Studio/Business/Constructor/DTOs/PageSectionEntityDTO.cs
  backend/Perflow.Studio/Business/Constructor/Handlers/CreatePageContainerHandler.cs
  backend/Perflow.Studio/Business/Constructor/Handlers/DeleteContainerHandler.cs
  backend/Perflow.Studio/Business/Constructor/Handlers/GetAllContainersViewsHandler.cs
  backend/Perflow.Studio/Business/Constructor/Handlers/PublishContainerHandler.cs
  backend/Perflow.Studio/Business/Constructor/Handlers/UpdatePageContainerHandler.cs
  backend/Perflow.Studio/Business/Constructor/Queries/GetAllContainersViewsQuery.cs
  backend/Perflow.Studio/Business/Constructor/Queries/PublishContainerQuery.cs
  backend/Perflow.Studio/Business/Songs/Mapping/ConstructorProfile.cs
  backend/Perflow.Studio/Controllers/ConstructorController.cs
  backend/Perflow.Studio/Domain/Entities/PageContainer.cs
  backend/Perflow.Studio/Domain/Entities/PageSection.cs
  backend/Perflow.Studio/Domain/Entities/PageSectionEntity.cs
  backend/Perflow.Studio/Domain/Enums/EntityType.cs
  backend/Perflow.Studio/Perflow.Studio.csproj
  backend/Perflow.Studio/Services/Extensions/DapperExtensions/ConstructorExtensions.cs
  backend/Perflow/Controllers/ConstructorController.cs
  backend/Perflow/Perflow.csproj
  backend/Perflow/Services/Implementations/ConstructorService.cs
  frontend/src/app/services/constructor.service.ts
Labels: enhancement

#308 Fix layout bugs
  frontend/src/app/modules/login-other/other-page/artist-applicant-page/artist-applicant-page.component.html
  frontend/src/app/modules/login-other/other-page/artist-applicant-page/artist-applicant-page.component.sass
  frontend/src/app/modules/main-content-container/main-content/main-content.component.sass
  frontend/src/app/modules/main-content-container/notifications/notifications.component.sass
  frontend/src/app/modules/main-content-container/profile-menu/profile-menu.component.sass
  frontend/src/app/modules/main/album-details/album-details.component.html
  frontend/src/app/modules/main/album-details/album-details.component.ts
  frontend/src/app/modules/main/main-home/main-home.component.sass
  frontend/src/app/modules/main/main-menu/main-menu.component.sass
  frontend/src/app/modules/main/playlist/playlist.component.sass
  frontend/src/app/modules/main/user-profile/user-profile.component.sass
  frontend/src/app/modules/main/view-playlist/view-playlist.component.html
  frontend/src/app/modules/main/view-playlist/view-playlist.component.sass
  frontend/src/app/modules/perflow-studio/albums-page/albums-page.component.sass
  frontend/src/app/modules/perflow-studio/applications-page/applications-page.component.sass
  frontend/src/app/modules/perflow-studio/constructor/containers-page/containers-page/containers-page.component.sass
  frontend/src/app/modules/perflow-studio/constructor/create-edit-container/create-edit-container/create-edit-container.component.sass
  frontend/src/app/modules/perflow-studio/create-edit-album/create-edit-album/create-edit-album.component.sass
  frontend/src/app/modules/perflow-studio/left-side-menu/left-side-menu.component.sass
  frontend/src/app/modules/perflow-studio/main-page/main-page.component.sass
  frontend/src/app/modules/perflow-studio/playlists-page/playlists-page.component.sass
  frontend/src/app/modules/register/user-registration-form/user-registration-form/user-registration-form.component.html
  frontend/src/app/modules/register/user-registration-form/user-registration-form/user-registration-form.component.sass
  frontend/src/app/modules/register/user-registration-form/user-registration-form/user-registration-form.component.ts
  frontend/src/app/services/album.service.ts
Labels: bug

#303 Notify participants
  backend/Perflow/Common/Helpers/PlaylistNotifier.cs
  backend/Perflow/Services/Extensions/ServiceExtensions.cs
  backend/Perflow/Services/Implementations/PlaylistService.cs
Labels: enhancement

#307 add album description; add image for Playlists "Recommendations" and "Your mix"
  backend/Perflow/Common/DTO/Albums/AlbumForViewDTO.cs
  backend/Perflow/Services/Implementations/AlbumsService.cs
  backend/Perflow/Services/Implementations/NotificationService.cs
  backend/Perflow/Services/Implementations/PlaylistService.cs
  backend/Perflow/Services/Interfaces/INotificationService.cs
  frontend/src/app/modules/main/album-details/album-details.component.html
  frontend/src/app/modules/main/album-details/album-details.component.sass
  frontend/src/app/modules/main/cards/your-mix-card/your-mix-card.component.html
  frontend/src/app/modules/main/view-playlist/view-playlist.component.html
  frontend/src/app/modules/main/view-playlist/view-playlist.component.sass
Labels: bug

#309 Fix styles
  frontend/src/app/modules/login-other/other-page/artist-applicant-page/artist-applicant-page.component.sass
Labels: bug

#311 Add song indexing
  backend/ApiGateway/ApiGateway/Configuration/Production/songRecognition.json
  backend/Perflow/Controllers/SongRecognitionController.cs
  backend/Perflow/Services/Extensions/ServiceExtensions.cs
  backend/Perflow/Services/Implementations/SongIndexingService.cs
  backend/Perflow/Services/Implementations/SongRecognitionService.cs
  backend/Perflow/Services/Interfaces/ISongIndexingService.cs
  backend/Perflow/Services/Interfaces/ISongRecognitionService.cs
  backend/Perflow/appsettings.json
  backend/Processor/Processor.ConsoleApp/Implementations/DefaultContainer.cs
  backend/Processor/Processor.ConsoleApp/Implementations/SongIndexingHandler.cs
  backend/Processor/Processor.ConsoleApp/Implementations/SongRecognitionHandler.cs
  backend/Processor/Processor.ConsoleApp/Interfaces/ISongsProcessingService.cs
  backend/Processor/Processor.ConsoleApp/Services/SongsProcessingService.cs
  backend/Processor/Processor.ConsoleApp/properties.json
  backend/Shared/Shared/Processor/Models/SongIndexingOptions.cs
  backend/Shared/Shared/Processor/Models/SongIndexingRabbitMQOptions.cs
  mobile/lib/services/playback/playback_sync_hub.dart
  mobile/lib/services/signalr/hub_factory_service.dart
Labels: enhancement

#312 Fix ffmpeg download
  backend/Processor/Processor.ConsoleApp/Implementations/SongProcessingHandler.cs
Labels: bug, important

#313 Bugfix/final fixes
  frontend/src/app/models/song/song.ts
  frontend/src/app/modules/main-content-container/music-components/queue/queue.component.ts
  frontend/src/app/modules/main-content-container/music-components/song-toolbar/song-toolbar.component.ts
  frontend/src/app/modules/main/album-details/album-details.component.ts
  frontend/src/app/modules/main/playlist/all/all.component.sass
  frontend/src/app/modules/perflow-studio/create-edit-album/create-edit-album/create-edit-album.component.html
  frontend/src/app/modules/perflow-studio/create-edit-album/create-edit-album/create-edit-album.component.sass
  frontend/src/app/modules/shared/create-edit-playlist/create-edit-playlist/create-edit-playlist.component.html
  frontend/src/app/modules/shared/create-edit-playlist/create-edit-playlist/create-edit-playlist.component.sass
  frontend/src/app/modules/shared/song-row/song-row.component.html
  frontend/src/app/modules/shared/song-row/song-row.component.ts
  frontend/src/app/modules/shared/songs-list/songs-list.component.html
  frontend/src/app/modules/shared/songs-list/songs-list.component.ts
  frontend/src/app/services/queue.service.ts
  frontend/src/app/services/song-toolbar.service.ts
Labels: bug

#314 Bugfix/final fixes 2
  frontend/src/app/modules/main/group-view/group-view.component.html
  frontend/src/app/modules/main/group-view/group-view.component.ts
  frontend/src/app/modules/main/main-menu/main-menu.component.html
  frontend/src/app/modules/perflow-studio/edit-group/edit-group/edit-group/edit-group.component.html
  frontend/src/app/modules/perflow-studio/edit-group/edit-group/edit-group/edit-group.component.ts
Labels: bug

#315 fix GetAlbumShortInfosByArtist
  backend/Perflow/Controllers/AlbumsController.cs
  backend/Perflow/Services/Implementations/AlbumsService.cs
Labels: bug
