Repository BinaryStudioAcademy/bsa-2021-perflow, pull requests merged in 2021-07, with the labels that each got.

#3 Add RabbitMQ
  backend/Shared/Shared.sln
  backend/Shared/Shared/RabbitMQ/RabbitMQWrapper.cs
  backend/Shared/Shared/Shared.csproj
Labels: help wanted

#10 add api gateway
  backend/ApiGateway/ApiGateway.sln
  backend/ApiGateway/ApiGateway/ApiGateway.csproj
  backend/ApiGateway/ApiGateway/Program.cs
  backend/ApiGateway/ApiGateway/Properties/launchSettings.json
  backend/ApiGateway/ApiGateway/Startup.cs
  backend/ApiGateway/ApiGateway/appsettings.Development.json
  backend/ApiGateway/ApiGateway/appsettings.json
  backend/ApiGateway/ApiGateway/configuration.json
Labels: enhancement

#6 Add and configure ESLint
  frontend/.eslintrc.json
  frontend/angular.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/app.component.spec.ts
  frontend/tsconfig.json
Labels: enhancement

#8 Feature/perflow-studio/dapper
  backend/Perflow.Studio/Business/Albums/DTOs/AlbumReadDTO.cs
  backend/Perflow.Studio/Business/Albums/DTOs/AlbumWriteDTO.cs
  backend/Perflow.Studio/Business/Playlists/DTOs/PlaylistReadDTO.cs
  backend/Perflow.Studio/Business/Playlists/DTOs/PlaylistWriteDTO.cs
  backend/Perflow.Studio/Business/Songs/DTOs/SongReadDTO.cs
  backend/Perflow.Studio/Business/Songs/DTOs/SongWriteDTO.cs
  backend/Perflow.Studio/Business/Songs/Handlers/CreateSongHandler.cs
  backend/Perflow.Studio/Business/Songs/Handlers/GetAllSongsHandler.cs
  backend/Perflow.Studio/Business/Songs/Handlers/GetSpecificSongHandler.cs
  backend/Perflow.Studio/Business/Users/DTOs/UserWriteDTO.cs
  backend/Perflow.Studio/Common/Implementations/DateProvider.cs
  backend/Perflow.Studio/Common/Interfaces/IDateProvider.cs
  backend/Perflow.Studio/Common/Interfaces/IDbConnectionFactory.cs
  backend/Perflow.Studio/Common/Interfaces/Repositories/IReadRepository.cs
  backend/Perflow.Studio/Common/Interfaces/Repositories/ISongsRepository.cs
  backend/Perflow.Studio/Common/Interfaces/Repositories/IWriteRepository.cs
  backend/Perflow.Studio/DataAccess/Extensions/RegisterRepositoryExtension.cs
  backend/Perflow.Studio/DataAccess/Implementations/DbConnectionFactory.cs
  backend/Perflow.Studio/DataAccess/Repositories/RegisterRepositoryExtension.cs
  backend/Perflow.Studio/DataAccess/Repositories/Repository.cs
  backend/Perflow.Studio/DataAccess/Repositories/RepositoryBase.cs
  backend/Perflow.Studio/DataAccess/Repositories/SongsRepository.cs
  backend/Perflow.Studio/Domain/Entities/Album.cs
  backend/Perflow.Studio/Domain/Entities/Playlist.cs
  backend/Perflow.Studio/Domain/Entities/Song.cs
  backend/Perflow.Studio/Domain/Enums/AlbumRegion.cs
  backend/Perflow.Studio/Domain/Enums/AlbumType.cs
  backend/Perflow.Studio/Domain/Enums/AuthorType.cs
  backend/Perflow.Studio/Perflow.Studio.csproj
  backend/Perflow.Studio/Startup.cs
  backend/Perflow.Studio/appsettings.json
Labels: help wanted

#7 Created global exceptions handler
  backend/Perflow.Studio/Perflow.Studio.csproj
  backend/Perflow.Studio/Startup.cs
  backend/Perflow/Controllers/PlaylistsController.cs
  backend/Perflow/Perflow.csproj
  backend/Perflow/Services/PlaylistService.cs
  backend/Perflow/Startup.cs
  backend/Shared/Shared.sln
  backend/Shared/Shared/ExceptionsHandler/Exceptions/BadRequestException.cs
  backend/Shared/Shared/ExceptionsHandler/Exceptions/ForbiddenException.cs
  backend/Shared/Shared/ExceptionsHandler/Exceptions/MethodNotAllowedException.cs
  backend/Shared/Shared/ExceptionsHandler/Exceptions/NotFoundExcepion.cs
  backend/Shared/Shared/ExceptionsHandler/Exceptions/RequestTimeoutException.cs
  backend/Shared/Shared/ExceptionsHandler/Exceptions/TooManyRequestsException.cs
  backend/Shared/Shared/ExceptionsHandler/Exceptions/UnauthorizedException.cs
  backend/Shared/Shared/ExceptionsHandler/Exceptions/UnavailableForLegalReasonsException.cs
  backend/Shared/Shared/ExceptionsHandler/Exceptions/UnsupportedMediaTypeException.cs
  backend/Shared/Shared/ExceptionsHandler/Extensions/ExceptionFilterExtensions.cs
  backend/Shared/Shared/ExceptionsHandler/Filters/CustomExceptionFilterAttribute.cs
  backend/Shared/Shared/Shared.csproj
Labels: enhancement

#11 Feature/http-service-wrapper
  .vscode/launch.json
  frontend/package-lock.json
  frontend/src/app/services/http-internal.service.ts
  frontend/src/environments/environment.prod.ts
  frontend/src/environments/environment.ts
Labels: enhancement, help wanted

#13 Feature/create-processor-project
  backend/Processor/Processor.ConsoleApp/Implementations/DefaultContainer.cs
  backend/Processor/Processor.ConsoleApp/Implementations/TestMessageHandler.cs
  backend/Processor/Processor.ConsoleApp/Interfaces/IAsyncMessageHandler.cs
  backend/Processor/Processor.ConsoleApp/Interfaces/IProcessor.cs
  backend/Processor/Processor.ConsoleApp/Processor.ConsoleApp.csproj
  backend/Processor/Processor.ConsoleApp/Processor.cs
  backend/Processor/Processor.ConsoleApp/Program.cs
  backend/Processor/Processor.ConsoleApp/properties.json
  backend/Processor/Processor.sln
  backend/Shared/Shared/AzureBlobStorage/Models/BlobDto.cs
  backend/Shared/Shared/RabbitMQ/Extensions/MessageExtensions.cs
  backend/Shared/Shared/RabbitMQ/Extensions/QueueSendExtensions.cs
  backend/Shared/Shared/RabbitMQ/Extensions/RegisterRabbitMQExtension.cs
  backend/Shared/Shared/RabbitMQ/Implementations/Queue.cs
  backend/Shared/Shared/RabbitMQ/Implementations/QueueFactory.cs
  backend/Shared/Shared/RabbitMQ/Implementations/RabbitMQConnectionFactory.cs
  backend/Shared/Shared/RabbitMQ/Interfaces/IQueue.cs
  backend/Shared/Shared/RabbitMQ/Interfaces/IQueueFactory.cs
  backend/Shared/Shared/RabbitMQ/Interfaces/IRabbitMQConnectionFactory.cs
  backend/Shared/Shared/RabbitMQ/Models/RabbitMQMessage.cs
  backend/Shared/Shared/RabbitMQ/Options/ExchangeOptions.cs
  backend/Shared/Shared/RabbitMQ/Options/QueueOptions.cs
  backend/Shared/Shared/RabbitMQ/Options/RabbitMQOptions.cs
  backend/Shared/Shared/RabbitMQ/RabbitMQWrapper.cs
  backend/Shared/Shared/Shared.csproj
Labels: enhancement, help wanted

#9 Feature/frontend routing and left side menu
  frontend/angular.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.component.html
  frontend/src/app/app.module.ts
  frontend/src/app/guard/auth.guard.ts
  frontend/src/app/moduls/auth/auth-routing.module.ts
  frontend/src/app/moduls/auth/auth.module.ts
  frontend/src/app/moduls/auth/landingpage/landingpage.component.html
  frontend/src/app/moduls/auth/landingpage/landingpage.component.sass
  frontend/src/app/moduls/auth/landingpage/landingpage.component.ts
  frontend/src/app/moduls/main/main-home/main-home.component.html
  frontend/src/app/moduls/main/main-home/main-home.component.sass
  frontend/src/app/moduls/main/main-home/main-home.component.spec.ts
  frontend/src/app/moduls/main/main-home/main-home.component.ts
  frontend/src/app/moduls/main/main-menu/main-menu.component.html
  frontend/src/app/moduls/main/main-menu/main-menu.component.sass
  frontend/src/app/moduls/main/main-menu/main-menu.component.spec.ts
  frontend/src/app/moduls/main/main-menu/main-menu.component.ts
  frontend/src/app/moduls/main/main-routing.module.ts
  frontend/src/app/moduls/main/main.module.ts
  frontend/src/app/moduls/main/playlist/playlist.component.html
  frontend/src/app/moduls/main/playlist/playlist.component.sass
  frontend/src/app/moduls/main/playlist/playlist.component.spec.ts
  frontend/src/app/moduls/main/playlist/playlist.component.ts
  frontend/src/app/moduls/main/search/search.component.html
  frontend/src/app/moduls/main/search/search.component.sass
  frontend/src/app/moduls/main/search/search.component.spec.ts
  frontend/src/app/moduls/main/search/search.component.ts
  frontend/src/app/moduls/main/songs/songs.component.html
  frontend/src/app/moduls/main/songs/songs.component.sass
  frontend/src/app/moduls/main/songs/songs.component.spec.ts
  frontend/src/app/moduls/main/songs/songs.component.ts
  frontend/src/app/services/auth.service.ts
Labels: enhancement

#15 add seeding
  backend/Perflow/Common/Security/SecurityHelper.cs
  backend/Perflow/DataAccess/Context/ModelBuilderExtensions.cs
  backend/Perflow/DataAccess/Context/PerflowContext.cs
  backend/Perflow/Migrations/PerflowContextModelSnapshot.cs
Labels: enhancement
